# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/masaüstü/yazılımileilgilihersey/onluk/osmanli oyun bot/anasayfa/form.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(642, 659)
        Widget.setStyleSheet("selection-color: rgb(170, 170, 255);\n"
"background-color: rgb(167, 167, 167);\n"
"alternate-background-color: rgb(85, 0, 0);\n"
"selection-background-color: rgb(85, 255, 127);\n"
"")
        self.scrollArea = QtWidgets.QScrollArea(Widget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 10, 631, 561))
        self.scrollArea.setStyleSheet("color: rgb(85, 170, 0);\n"
"selection-color: rgb(170, 170, 255);\n"
"border-top-color: rgb(255, 0, 0);\n"
"background-color: rgb(70, 70, 70);")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(-423, -522, 1031, 1060))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.email_20 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.email_20.setMinimumSize(QtCore.QSize(240, 41))
        self.email_20.setMaximumSize(QtCore.QSize(240, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.email_20.setFont(font)
        self.email_20.setObjectName("email_20")
        self.gridLayout.addWidget(self.email_20, 20, 1, 1, 1)
        self.sira_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.sira_13.setMinimumSize(QtCore.QSize(65, 36))
        self.sira_13.setMaximumSize(QtCore.QSize(65, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sira_13.setFont(font)
        self.sira_13.setObjectName("sira_13")
        self.gridLayout.addWidget(self.sira_13, 13, 0, 1, 1)
        self.email_18 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.email_18.setMinimumSize(QtCore.QSize(240, 41))
        self.email_18.setMaximumSize(QtCore.QSize(240, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.email_18.setFont(font)
        self.email_18.setObjectName("email_18")
        self.gridLayout.addWidget(self.email_18, 18, 1, 1, 1)
        self.sira_20 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.sira_20.setMinimumSize(QtCore.QSize(65, 36))
        self.sira_20.setMaximumSize(QtCore.QSize(65, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sira_20.setFont(font)
        self.sira_20.setObjectName("sira_20")
        self.gridLayout.addWidget(self.sira_20, 20, 0, 1, 1)
        self.sifre_11 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.sifre_11.setMinimumSize(QtCore.QSize(170, 41))
        self.sifre_11.setMaximumSize(QtCore.QSize(170, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sifre_11.setFont(font)
        self.sifre_11.setObjectName("sifre_11")
        self.gridLayout.addWidget(self.sifre_11, 11, 2, 1, 1)
        self.email_3 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.email_3.setMinimumSize(QtCore.QSize(240, 41))
        self.email_3.setMaximumSize(QtCore.QSize(240, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.email_3.setFont(font)
        self.email_3.setObjectName("email_3")
        self.gridLayout.addWidget(self.email_3, 3, 1, 1, 1)
        self.sira_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.sira_7.setMinimumSize(QtCore.QSize(65, 36))
        self.sira_7.setMaximumSize(QtCore.QSize(65, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sira_7.setFont(font)
        self.sira_7.setObjectName("sira_7")
        self.gridLayout.addWidget(self.sira_7, 7, 0, 1, 1)
        self.email_5 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.email_5.setMinimumSize(QtCore.QSize(240, 41))
        self.email_5.setMaximumSize(QtCore.QSize(240, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.email_5.setFont(font)
        self.email_5.setObjectName("email_5")
        self.gridLayout.addWidget(self.email_5, 5, 1, 1, 1)
        self.sifre_isim = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.sifre_isim.setMinimumSize(QtCore.QSize(65, 36))
        self.sifre_isim.setMaximumSize(QtCore.QSize(65, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sifre_isim.setFont(font)
        self.sifre_isim.setObjectName("sifre_isim")
        self.gridLayout.addWidget(self.sifre_isim, 0, 2, 1, 1)
        self.email_16 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.email_16.setMinimumSize(QtCore.QSize(240, 41))
        self.email_16.setMaximumSize(QtCore.QSize(240, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.email_16.setFont(font)
        self.email_16.setObjectName("email_16")
        self.gridLayout.addWidget(self.email_16, 16, 1, 1, 1)
        self.email_isim = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.email_isim.setMinimumSize(QtCore.QSize(65, 36))
        self.email_isim.setMaximumSize(QtCore.QSize(65, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.email_isim.setFont(font)
        self.email_isim.setObjectName("email_isim")
        self.gridLayout.addWidget(self.email_isim, 0, 1, 1, 1)
        self.sifre_2 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.sifre_2.setMinimumSize(QtCore.QSize(170, 41))
        self.sifre_2.setMaximumSize(QtCore.QSize(170, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sifre_2.setFont(font)
        self.sifre_2.setObjectName("sifre_2")
        self.gridLayout.addWidget(self.sifre_2, 2, 2, 1, 1)
        self.sira_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.sira_5.setMinimumSize(QtCore.QSize(65, 36))
        self.sira_5.setMaximumSize(QtCore.QSize(65, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sira_5.setFont(font)
        self.sira_5.setObjectName("sira_5")
        self.gridLayout.addWidget(self.sira_5, 5, 0, 1, 1)
        self.sifre_7 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.sifre_7.setMinimumSize(QtCore.QSize(170, 41))
        self.sifre_7.setMaximumSize(QtCore.QSize(170, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sifre_7.setFont(font)
        self.sifre_7.setObjectName("sifre_7")
        self.gridLayout.addWidget(self.sifre_7, 7, 2, 1, 1)
        self.sifre_9 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.sifre_9.setMinimumSize(QtCore.QSize(170, 41))
        self.sifre_9.setMaximumSize(QtCore.QSize(170, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sifre_9.setFont(font)
        self.sifre_9.setObjectName("sifre_9")
        self.gridLayout.addWidget(self.sifre_9, 9, 2, 1, 1)
        self.sira_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.sira_11.setMinimumSize(QtCore.QSize(65, 36))
        self.sira_11.setMaximumSize(QtCore.QSize(65, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sira_11.setFont(font)
        self.sira_11.setObjectName("sira_11")
        self.gridLayout.addWidget(self.sira_11, 11, 0, 1, 1)
        self.email_19 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.email_19.setMinimumSize(QtCore.QSize(240, 41))
        self.email_19.setMaximumSize(QtCore.QSize(240, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.email_19.setFont(font)
        self.email_19.setObjectName("email_19")
        self.gridLayout.addWidget(self.email_19, 19, 1, 1, 1)
        self.sifre_18 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.sifre_18.setMinimumSize(QtCore.QSize(170, 41))
        self.sifre_18.setMaximumSize(QtCore.QSize(170, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sifre_18.setFont(font)
        self.sifre_18.setObjectName("sifre_18")
        self.gridLayout.addWidget(self.sifre_18, 18, 2, 1, 1)
        self.email = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.email.setMinimumSize(QtCore.QSize(240, 41))
        self.email.setMaximumSize(QtCore.QSize(240, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.email.setFont(font)
        self.email.setObjectName("email")
        self.gridLayout.addWidget(self.email, 1, 1, 1, 1)
        self.sifre_20 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.sifre_20.setMinimumSize(QtCore.QSize(170, 41))
        self.sifre_20.setMaximumSize(QtCore.QSize(170, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sifre_20.setFont(font)
        self.sifre_20.setObjectName("sifre_20")
        self.gridLayout.addWidget(self.sifre_20, 20, 2, 1, 1)
        self.sira_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.sira_8.setMinimumSize(QtCore.QSize(65, 36))
        self.sira_8.setMaximumSize(QtCore.QSize(65, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sira_8.setFont(font)
        self.sira_8.setObjectName("sira_8")
        self.gridLayout.addWidget(self.sira_8, 8, 0, 1, 1)
        self.email_14 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.email_14.setMinimumSize(QtCore.QSize(240, 41))
        self.email_14.setMaximumSize(QtCore.QSize(240, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.email_14.setFont(font)
        self.email_14.setObjectName("email_14")
        self.gridLayout.addWidget(self.email_14, 14, 1, 1, 1)
        self.sifre_13 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.sifre_13.setMinimumSize(QtCore.QSize(170, 41))
        self.sifre_13.setMaximumSize(QtCore.QSize(170, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sifre_13.setFont(font)
        self.sifre_13.setObjectName("sifre_13")
        self.gridLayout.addWidget(self.sifre_13, 13, 2, 1, 1)
        self.sifre_10 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.sifre_10.setMinimumSize(QtCore.QSize(170, 41))
        self.sifre_10.setMaximumSize(QtCore.QSize(170, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sifre_10.setFont(font)
        self.sifre_10.setObjectName("sifre_10")
        self.gridLayout.addWidget(self.sifre_10, 10, 2, 1, 1)
        self.sira_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.sira_4.setMinimumSize(QtCore.QSize(65, 36))
        self.sira_4.setMaximumSize(QtCore.QSize(65, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sira_4.setFont(font)
        self.sira_4.setObjectName("sira_4")
        self.gridLayout.addWidget(self.sira_4, 4, 0, 1, 1)
        self.sifre_14 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.sifre_14.setMinimumSize(QtCore.QSize(170, 41))
        self.sifre_14.setMaximumSize(QtCore.QSize(170, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sifre_14.setFont(font)
        self.sifre_14.setObjectName("sifre_14")
        self.gridLayout.addWidget(self.sifre_14, 14, 2, 1, 1)
        self.sira_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.sira_14.setMinimumSize(QtCore.QSize(65, 36))
        self.sira_14.setMaximumSize(QtCore.QSize(65, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sira_14.setFont(font)
        self.sira_14.setObjectName("sira_14")
        self.gridLayout.addWidget(self.sira_14, 14, 0, 1, 1)
        self.email_8 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.email_8.setMinimumSize(QtCore.QSize(240, 41))
        self.email_8.setMaximumSize(QtCore.QSize(240, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.email_8.setFont(font)
        self.email_8.setObjectName("email_8")
        self.gridLayout.addWidget(self.email_8, 8, 1, 1, 1)
        self.email_17 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.email_17.setMinimumSize(QtCore.QSize(240, 41))
        self.email_17.setMaximumSize(QtCore.QSize(240, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.email_17.setFont(font)
        self.email_17.setObjectName("email_17")
        self.gridLayout.addWidget(self.email_17, 17, 1, 1, 1)
        self.sifre_17 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.sifre_17.setMinimumSize(QtCore.QSize(170, 41))
        self.sifre_17.setMaximumSize(QtCore.QSize(170, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sifre_17.setFont(font)
        self.sifre_17.setObjectName("sifre_17")
        self.gridLayout.addWidget(self.sifre_17, 17, 2, 1, 1)
        self.sifre_3 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.sifre_3.setMinimumSize(QtCore.QSize(170, 41))
        self.sifre_3.setMaximumSize(QtCore.QSize(170, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sifre_3.setFont(font)
        self.sifre_3.setObjectName("sifre_3")
        self.gridLayout.addWidget(self.sifre_3, 3, 2, 1, 1)
        self.sira_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.sira_9.setMinimumSize(QtCore.QSize(65, 36))
        self.sira_9.setMaximumSize(QtCore.QSize(65, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sira_9.setFont(font)
        self.sira_9.setObjectName("sira_9")
        self.gridLayout.addWidget(self.sira_9, 9, 0, 1, 1)
        self.email_6 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.email_6.setMinimumSize(QtCore.QSize(240, 41))
        self.email_6.setMaximumSize(QtCore.QSize(240, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.email_6.setFont(font)
        self.email_6.setObjectName("email_6")
        self.gridLayout.addWidget(self.email_6, 6, 1, 1, 1)
        self.sira_19 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.sira_19.setMinimumSize(QtCore.QSize(65, 36))
        self.sira_19.setMaximumSize(QtCore.QSize(65, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sira_19.setFont(font)
        self.sira_19.setObjectName("sira_19")
        self.gridLayout.addWidget(self.sira_19, 19, 0, 1, 1)
        self.email_9 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.email_9.setMinimumSize(QtCore.QSize(240, 41))
        self.email_9.setMaximumSize(QtCore.QSize(240, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.email_9.setFont(font)
        self.email_9.setObjectName("email_9")
        self.gridLayout.addWidget(self.email_9, 9, 1, 1, 1)
        self.email_2 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.email_2.setMinimumSize(QtCore.QSize(240, 41))
        self.email_2.setMaximumSize(QtCore.QSize(240, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.email_2.setFont(font)
        self.email_2.setObjectName("email_2")
        self.gridLayout.addWidget(self.email_2, 2, 1, 1, 1)
        self.email_7 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.email_7.setMinimumSize(QtCore.QSize(240, 41))
        self.email_7.setMaximumSize(QtCore.QSize(240, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.email_7.setFont(font)
        self.email_7.setObjectName("email_7")
        self.gridLayout.addWidget(self.email_7, 7, 1, 1, 1)
        self.sira_16 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.sira_16.setMinimumSize(QtCore.QSize(65, 36))
        self.sira_16.setMaximumSize(QtCore.QSize(65, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sira_16.setFont(font)
        self.sira_16.setObjectName("sira_16")
        self.gridLayout.addWidget(self.sira_16, 16, 0, 1, 1)
        self.sifre_19 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.sifre_19.setMinimumSize(QtCore.QSize(170, 41))
        self.sifre_19.setMaximumSize(QtCore.QSize(170, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sifre_19.setFont(font)
        self.sifre_19.setObjectName("sifre_19")
        self.gridLayout.addWidget(self.sifre_19, 19, 2, 1, 1)
        self.sifre_15 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.sifre_15.setMinimumSize(QtCore.QSize(170, 41))
        self.sifre_15.setMaximumSize(QtCore.QSize(170, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sifre_15.setFont(font)
        self.sifre_15.setObjectName("sifre_15")
        self.gridLayout.addWidget(self.sifre_15, 15, 2, 1, 1)
        self.sira_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.sira_12.setMinimumSize(QtCore.QSize(65, 36))
        self.sira_12.setMaximumSize(QtCore.QSize(65, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sira_12.setFont(font)
        self.sira_12.setObjectName("sira_12")
        self.gridLayout.addWidget(self.sira_12, 12, 0, 1, 1)
        self.email_11 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.email_11.setMinimumSize(QtCore.QSize(240, 41))
        self.email_11.setMaximumSize(QtCore.QSize(240, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.email_11.setFont(font)
        self.email_11.setObjectName("email_11")
        self.gridLayout.addWidget(self.email_11, 11, 1, 1, 1)
        self.sifre_16 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.sifre_16.setMinimumSize(QtCore.QSize(170, 41))
        self.sifre_16.setMaximumSize(QtCore.QSize(170, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sifre_16.setFont(font)
        self.sifre_16.setObjectName("sifre_16")
        self.gridLayout.addWidget(self.sifre_16, 16, 2, 1, 1)
        self.sira_17 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.sira_17.setMinimumSize(QtCore.QSize(65, 36))
        self.sira_17.setMaximumSize(QtCore.QSize(65, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sira_17.setFont(font)
        self.sira_17.setObjectName("sira_17")
        self.gridLayout.addWidget(self.sira_17, 17, 0, 1, 1)
        self.sifre = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.sifre.setMinimumSize(QtCore.QSize(170, 41))
        self.sifre.setMaximumSize(QtCore.QSize(170, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sifre.setFont(font)
        self.sifre.setObjectName("sifre")
        self.gridLayout.addWidget(self.sifre, 1, 2, 1, 1)
        self.sifre_8 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.sifre_8.setMinimumSize(QtCore.QSize(170, 41))
        self.sifre_8.setMaximumSize(QtCore.QSize(170, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sifre_8.setFont(font)
        self.sifre_8.setObjectName("sifre_8")
        self.gridLayout.addWidget(self.sifre_8, 8, 2, 1, 1)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.lastlogin = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lastlogin.setMinimumSize(QtCore.QSize(150, 41))
        self.lastlogin.setMaximumSize(QtCore.QSize(131, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lastlogin.setFont(font)
        self.lastlogin.setObjectName("lastlogin")
        self.gridLayout_8.addWidget(self.lastlogin, 0, 1, 1, 1)
        self.gold = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.gold.setMinimumSize(QtCore.QSize(235, 41))
        self.gold.setMaximumSize(QtCore.QSize(131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gold.setFont(font)
        self.gold.setObjectName("gold")
        self.gridLayout_8.addWidget(self.gold, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_8, 1, 4, 1, 1)
        self.sifre_4 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.sifre_4.setMinimumSize(QtCore.QSize(170, 41))
        self.sifre_4.setMaximumSize(QtCore.QSize(170, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sifre_4.setFont(font)
        self.sifre_4.setObjectName("sifre_4")
        self.gridLayout.addWidget(self.sifre_4, 4, 2, 1, 1)
        self.sira_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.sira_10.setMinimumSize(QtCore.QSize(65, 36))
        self.sira_10.setMaximumSize(QtCore.QSize(65, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sira_10.setFont(font)
        self.sira_10.setObjectName("sira_10")
        self.gridLayout.addWidget(self.sira_10, 10, 0, 1, 1)
        self.email_13 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.email_13.setMinimumSize(QtCore.QSize(240, 41))
        self.email_13.setMaximumSize(QtCore.QSize(240, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.email_13.setFont(font)
        self.email_13.setObjectName("email_13")
        self.gridLayout.addWidget(self.email_13, 13, 1, 1, 1)
        self.sira_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.sira_6.setMinimumSize(QtCore.QSize(65, 36))
        self.sira_6.setMaximumSize(QtCore.QSize(65, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sira_6.setFont(font)
        self.sira_6.setObjectName("sira_6")
        self.gridLayout.addWidget(self.sira_6, 6, 0, 1, 1)
        self.email_4 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.email_4.setMinimumSize(QtCore.QSize(240, 41))
        self.email_4.setMaximumSize(QtCore.QSize(240, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.email_4.setFont(font)
        self.email_4.setObjectName("email_4")
        self.gridLayout.addWidget(self.email_4, 4, 1, 1, 1)
        self.sira_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.sira_3.setMinimumSize(QtCore.QSize(65, 36))
        self.sira_3.setMaximumSize(QtCore.QSize(65, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sira_3.setFont(font)
        self.sira_3.setObjectName("sira_3")
        self.gridLayout.addWidget(self.sira_3, 3, 0, 1, 1)
        self.sira = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.sira.setMinimumSize(QtCore.QSize(65, 36))
        self.sira.setMaximumSize(QtCore.QSize(65, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sira.setFont(font)
        self.sira.setObjectName("sira")
        self.gridLayout.addWidget(self.sira, 1, 0, 1, 1)
        self.email_10 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.email_10.setMinimumSize(QtCore.QSize(240, 41))
        self.email_10.setMaximumSize(QtCore.QSize(240, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.email_10.setFont(font)
        self.email_10.setObjectName("email_10")
        self.gridLayout.addWidget(self.email_10, 10, 1, 1, 1)
        self.sira_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.sira_15.setMinimumSize(QtCore.QSize(65, 36))
        self.sira_15.setMaximumSize(QtCore.QSize(65, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sira_15.setFont(font)
        self.sira_15.setObjectName("sira_15")
        self.gridLayout.addWidget(self.sira_15, 15, 0, 1, 1)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.lastlogin_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lastlogin_2.setMinimumSize(QtCore.QSize(150, 41))
        self.lastlogin_2.setMaximumSize(QtCore.QSize(131, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lastlogin_2.setFont(font)
        self.lastlogin_2.setObjectName("lastlogin_2")
        self.gridLayout_10.addWidget(self.lastlogin_2, 0, 1, 1, 1)
        self.gold_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.gold_2.setMinimumSize(QtCore.QSize(235, 41))
        self.gold_2.setMaximumSize(QtCore.QSize(131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gold_2.setFont(font)
        self.gold_2.setObjectName("gold_2")
        self.gridLayout_10.addWidget(self.gold_2, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_10, 2, 4, 1, 1)
        self.sira_18 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.sira_18.setMinimumSize(QtCore.QSize(65, 36))
        self.sira_18.setMaximumSize(QtCore.QSize(65, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sira_18.setFont(font)
        self.sira_18.setObjectName("sira_18")
        self.gridLayout.addWidget(self.sira_18, 18, 0, 1, 1)
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.gold_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.gold_3.setMinimumSize(QtCore.QSize(235, 41))
        self.gold_3.setMaximumSize(QtCore.QSize(131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gold_3.setFont(font)
        self.gold_3.setObjectName("gold_3")
        self.gridLayout_11.addWidget(self.gold_3, 0, 0, 1, 1)
        self.lastlogin_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lastlogin_3.setMinimumSize(QtCore.QSize(150, 41))
        self.lastlogin_3.setMaximumSize(QtCore.QSize(131, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lastlogin_3.setFont(font)
        self.lastlogin_3.setObjectName("lastlogin_3")
        self.gridLayout_11.addWidget(self.lastlogin_3, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_11, 3, 4, 1, 1)
        self.sira_isim = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.sira_isim.setMinimumSize(QtCore.QSize(65, 36))
        self.sira_isim.setMaximumSize(QtCore.QSize(65, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sira_isim.setFont(font)
        self.sira_isim.setObjectName("sira_isim")
        self.gridLayout.addWidget(self.sira_isim, 0, 0, 1, 1)
        self.sira_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.sira_2.setMinimumSize(QtCore.QSize(65, 36))
        self.sira_2.setMaximumSize(QtCore.QSize(65, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sira_2.setFont(font)
        self.sira_2.setObjectName("sira_2")
        self.gridLayout.addWidget(self.sira_2, 2, 0, 1, 1)
        self.email_15 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.email_15.setMinimumSize(QtCore.QSize(240, 41))
        self.email_15.setMaximumSize(QtCore.QSize(240, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.email_15.setFont(font)
        self.email_15.setObjectName("email_15")
        self.gridLayout.addWidget(self.email_15, 15, 1, 1, 1)
        self.sifre_6 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.sifre_6.setMinimumSize(QtCore.QSize(170, 41))
        self.sifre_6.setMaximumSize(QtCore.QSize(170, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sifre_6.setFont(font)
        self.sifre_6.setObjectName("sifre_6")
        self.gridLayout.addWidget(self.sifre_6, 6, 2, 1, 1)
        self.sifre_5 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.sifre_5.setMinimumSize(QtCore.QSize(170, 41))
        self.sifre_5.setMaximumSize(QtCore.QSize(170, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sifre_5.setFont(font)
        self.sifre_5.setObjectName("sifre_5")
        self.gridLayout.addWidget(self.sifre_5, 5, 2, 1, 1)
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.lastlogin_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lastlogin_4.setMinimumSize(QtCore.QSize(150, 41))
        self.lastlogin_4.setMaximumSize(QtCore.QSize(131, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lastlogin_4.setFont(font)
        self.lastlogin_4.setObjectName("lastlogin_4")
        self.gridLayout_12.addWidget(self.lastlogin_4, 0, 1, 1, 1)
        self.gold_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.gold_4.setMinimumSize(QtCore.QSize(235, 41))
        self.gold_4.setMaximumSize(QtCore.QSize(131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gold_4.setFont(font)
        self.gold_4.setObjectName("gold_4")
        self.gridLayout_12.addWidget(self.gold_4, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_12, 4, 4, 1, 1)
        self.gridLayout_21 = QtWidgets.QGridLayout()
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.gold_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.gold_13.setMinimumSize(QtCore.QSize(235, 41))
        self.gold_13.setMaximumSize(QtCore.QSize(131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gold_13.setFont(font)
        self.gold_13.setObjectName("gold_13")
        self.gridLayout_21.addWidget(self.gold_13, 0, 0, 1, 1)
        self.lastlogin_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lastlogin_13.setMinimumSize(QtCore.QSize(150, 41))
        self.lastlogin_13.setMaximumSize(QtCore.QSize(131, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lastlogin_13.setFont(font)
        self.lastlogin_13.setObjectName("lastlogin_13")
        self.gridLayout_21.addWidget(self.lastlogin_13, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_21, 13, 4, 1, 1)
        self.gridLayout_17 = QtWidgets.QGridLayout()
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.lastlogin_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lastlogin_9.setMinimumSize(QtCore.QSize(150, 41))
        self.lastlogin_9.setMaximumSize(QtCore.QSize(131, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lastlogin_9.setFont(font)
        self.lastlogin_9.setObjectName("lastlogin_9")
        self.gridLayout_17.addWidget(self.lastlogin_9, 0, 1, 1, 1)
        self.gold_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.gold_9.setMinimumSize(QtCore.QSize(235, 41))
        self.gold_9.setMaximumSize(QtCore.QSize(131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gold_9.setFont(font)
        self.gold_9.setObjectName("gold_9")
        self.gridLayout_17.addWidget(self.gold_9, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_17, 9, 4, 1, 1)
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.gold_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.gold_7.setMinimumSize(QtCore.QSize(235, 41))
        self.gold_7.setMaximumSize(QtCore.QSize(131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gold_7.setFont(font)
        self.gold_7.setObjectName("gold_7")
        self.gridLayout_15.addWidget(self.gold_7, 0, 0, 1, 1)
        self.lastlogin_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lastlogin_7.setMinimumSize(QtCore.QSize(150, 41))
        self.lastlogin_7.setMaximumSize(QtCore.QSize(131, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lastlogin_7.setFont(font)
        self.lastlogin_7.setObjectName("lastlogin_7")
        self.gridLayout_15.addWidget(self.lastlogin_7, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_15, 7, 4, 1, 1)
        self.gridLayout_18 = QtWidgets.QGridLayout()
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.lastlogin_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lastlogin_10.setMinimumSize(QtCore.QSize(150, 41))
        self.lastlogin_10.setMaximumSize(QtCore.QSize(131, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lastlogin_10.setFont(font)
        self.lastlogin_10.setObjectName("lastlogin_10")
        self.gridLayout_18.addWidget(self.lastlogin_10, 0, 1, 1, 1)
        self.gold_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.gold_10.setMinimumSize(QtCore.QSize(235, 41))
        self.gold_10.setMaximumSize(QtCore.QSize(131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gold_10.setFont(font)
        self.gold_10.setObjectName("gold_10")
        self.gridLayout_18.addWidget(self.gold_10, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_18, 10, 4, 1, 1)
        self.gridLayout_19 = QtWidgets.QGridLayout()
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.gold_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.gold_11.setMinimumSize(QtCore.QSize(235, 41))
        self.gold_11.setMaximumSize(QtCore.QSize(131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gold_11.setFont(font)
        self.gold_11.setObjectName("gold_11")
        self.gridLayout_19.addWidget(self.gold_11, 0, 0, 1, 1)
        self.lastlogin_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lastlogin_11.setMinimumSize(QtCore.QSize(150, 41))
        self.lastlogin_11.setMaximumSize(QtCore.QSize(131, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lastlogin_11.setFont(font)
        self.lastlogin_11.setObjectName("lastlogin_11")
        self.gridLayout_19.addWidget(self.lastlogin_11, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_19, 11, 4, 1, 1)
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.gold_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.gold_5.setMinimumSize(QtCore.QSize(235, 41))
        self.gold_5.setMaximumSize(QtCore.QSize(131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gold_5.setFont(font)
        self.gold_5.setObjectName("gold_5")
        self.gridLayout_13.addWidget(self.gold_5, 0, 0, 1, 1)
        self.lastlogin_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lastlogin_5.setMinimumSize(QtCore.QSize(150, 41))
        self.lastlogin_5.setMaximumSize(QtCore.QSize(131, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lastlogin_5.setFont(font)
        self.lastlogin_5.setObjectName("lastlogin_5")
        self.gridLayout_13.addWidget(self.lastlogin_5, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_13, 5, 4, 1, 1)
        self.gridLayout_20 = QtWidgets.QGridLayout()
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.gold_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.gold_12.setMinimumSize(QtCore.QSize(235, 41))
        self.gold_12.setMaximumSize(QtCore.QSize(131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gold_12.setFont(font)
        self.gold_12.setObjectName("gold_12")
        self.gridLayout_20.addWidget(self.gold_12, 0, 0, 1, 1)
        self.lastlogin_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lastlogin_12.setMinimumSize(QtCore.QSize(150, 41))
        self.lastlogin_12.setMaximumSize(QtCore.QSize(131, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lastlogin_12.setFont(font)
        self.lastlogin_12.setObjectName("lastlogin_12")
        self.gridLayout_20.addWidget(self.lastlogin_12, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_20, 12, 4, 1, 1)
        self.gridLayout_22 = QtWidgets.QGridLayout()
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.lastlogin_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lastlogin_14.setMinimumSize(QtCore.QSize(150, 41))
        self.lastlogin_14.setMaximumSize(QtCore.QSize(131, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lastlogin_14.setFont(font)
        self.lastlogin_14.setObjectName("lastlogin_14")
        self.gridLayout_22.addWidget(self.lastlogin_14, 0, 1, 1, 1)
        self.gold_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.gold_14.setMinimumSize(QtCore.QSize(235, 41))
        self.gold_14.setMaximumSize(QtCore.QSize(131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gold_14.setFont(font)
        self.gold_14.setObjectName("gold_14")
        self.gridLayout_22.addWidget(self.gold_14, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_22, 14, 4, 1, 1)
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.gold_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.gold_6.setMinimumSize(QtCore.QSize(235, 41))
        self.gold_6.setMaximumSize(QtCore.QSize(131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gold_6.setFont(font)
        self.gold_6.setObjectName("gold_6")
        self.gridLayout_14.addWidget(self.gold_6, 0, 0, 1, 1)
        self.lastlogin_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lastlogin_6.setMinimumSize(QtCore.QSize(150, 41))
        self.lastlogin_6.setMaximumSize(QtCore.QSize(131, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lastlogin_6.setFont(font)
        self.lastlogin_6.setObjectName("lastlogin_6")
        self.gridLayout_14.addWidget(self.lastlogin_6, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_14, 6, 4, 1, 1)
        self.gridLayout_23 = QtWidgets.QGridLayout()
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.gold_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.gold_15.setMinimumSize(QtCore.QSize(235, 41))
        self.gold_15.setMaximumSize(QtCore.QSize(131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gold_15.setFont(font)
        self.gold_15.setObjectName("gold_15")
        self.gridLayout_23.addWidget(self.gold_15, 0, 0, 1, 1)
        self.lastlogin_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lastlogin_15.setMinimumSize(QtCore.QSize(150, 41))
        self.lastlogin_15.setMaximumSize(QtCore.QSize(131, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lastlogin_15.setFont(font)
        self.lastlogin_15.setObjectName("lastlogin_15")
        self.gridLayout_23.addWidget(self.lastlogin_15, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_23, 15, 4, 1, 1)
        self.gridLayout_16 = QtWidgets.QGridLayout()
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.lastlogin_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lastlogin_8.setMinimumSize(QtCore.QSize(150, 41))
        self.lastlogin_8.setMaximumSize(QtCore.QSize(131, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lastlogin_8.setFont(font)
        self.lastlogin_8.setObjectName("lastlogin_8")
        self.gridLayout_16.addWidget(self.lastlogin_8, 0, 1, 1, 1)
        self.gold_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.gold_8.setMinimumSize(QtCore.QSize(235, 41))
        self.gold_8.setMaximumSize(QtCore.QSize(131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gold_8.setFont(font)
        self.gold_8.setObjectName("gold_8")
        self.gridLayout_16.addWidget(self.gold_8, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_16, 8, 4, 1, 1)
        self.gridLayout_24 = QtWidgets.QGridLayout()
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.gold_16 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.gold_16.setMinimumSize(QtCore.QSize(235, 41))
        self.gold_16.setMaximumSize(QtCore.QSize(131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gold_16.setFont(font)
        self.gold_16.setObjectName("gold_16")
        self.gridLayout_24.addWidget(self.gold_16, 0, 0, 1, 1)
        self.lastlogin_16 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lastlogin_16.setMinimumSize(QtCore.QSize(150, 41))
        self.lastlogin_16.setMaximumSize(QtCore.QSize(131, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lastlogin_16.setFont(font)
        self.lastlogin_16.setObjectName("lastlogin_16")
        self.gridLayout_24.addWidget(self.lastlogin_16, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_24, 16, 4, 1, 1)
        self.gridLayout_28 = QtWidgets.QGridLayout()
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.gold_20 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.gold_20.setMinimumSize(QtCore.QSize(235, 41))
        self.gold_20.setMaximumSize(QtCore.QSize(131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gold_20.setFont(font)
        self.gold_20.setObjectName("gold_20")
        self.gridLayout_28.addWidget(self.gold_20, 0, 0, 1, 1)
        self.lastlogin_20 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lastlogin_20.setMinimumSize(QtCore.QSize(150, 41))
        self.lastlogin_20.setMaximumSize(QtCore.QSize(131, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lastlogin_20.setFont(font)
        self.lastlogin_20.setObjectName("lastlogin_20")
        self.gridLayout_28.addWidget(self.lastlogin_20, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_28, 20, 4, 1, 1)
        self.gridLayout_26 = QtWidgets.QGridLayout()
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.lastlogin_18 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lastlogin_18.setMinimumSize(QtCore.QSize(150, 41))
        self.lastlogin_18.setMaximumSize(QtCore.QSize(131, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lastlogin_18.setFont(font)
        self.lastlogin_18.setObjectName("lastlogin_18")
        self.gridLayout_26.addWidget(self.lastlogin_18, 0, 1, 1, 1)
        self.gold_18 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.gold_18.setMinimumSize(QtCore.QSize(235, 41))
        self.gold_18.setMaximumSize(QtCore.QSize(131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gold_18.setFont(font)
        self.gold_18.setObjectName("gold_18")
        self.gridLayout_26.addWidget(self.gold_18, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_26, 18, 4, 1, 1)
        self.gridLayout_27 = QtWidgets.QGridLayout()
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.lastlogin_19 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lastlogin_19.setMinimumSize(QtCore.QSize(150, 41))
        self.lastlogin_19.setMaximumSize(QtCore.QSize(131, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lastlogin_19.setFont(font)
        self.lastlogin_19.setObjectName("lastlogin_19")
        self.gridLayout_27.addWidget(self.lastlogin_19, 0, 1, 1, 1)
        self.gold_19 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.gold_19.setMinimumSize(QtCore.QSize(235, 41))
        self.gold_19.setMaximumSize(QtCore.QSize(131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gold_19.setFont(font)
        self.gold_19.setObjectName("gold_19")
        self.gridLayout_27.addWidget(self.gold_19, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_27, 19, 4, 1, 1)
        self.email_12 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.email_12.setMinimumSize(QtCore.QSize(240, 41))
        self.email_12.setMaximumSize(QtCore.QSize(240, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.email_12.setFont(font)
        self.email_12.setObjectName("email_12")
        self.gridLayout.addWidget(self.email_12, 12, 1, 1, 1)
        self.sifre_12 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.sifre_12.setMinimumSize(QtCore.QSize(170, 41))
        self.sifre_12.setMaximumSize(QtCore.QSize(170, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sifre_12.setFont(font)
        self.sifre_12.setObjectName("sifre_12")
        self.gridLayout.addWidget(self.sifre_12, 12, 2, 1, 1)
        self.gridLayout_25 = QtWidgets.QGridLayout()
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.lastlogin_17 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lastlogin_17.setMinimumSize(QtCore.QSize(150, 41))
        self.lastlogin_17.setMaximumSize(QtCore.QSize(131, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lastlogin_17.setFont(font)
        self.lastlogin_17.setObjectName("lastlogin_17")
        self.gridLayout_25.addWidget(self.lastlogin_17, 0, 1, 1, 1)
        self.gold_17 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.gold_17.setMinimumSize(QtCore.QSize(235, 41))
        self.gold_17.setMaximumSize(QtCore.QSize(131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gold_17.setFont(font)
        self.gold_17.setObjectName("gold_17")
        self.gridLayout_25.addWidget(self.gold_17, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_25, 17, 4, 1, 1)
        self.log_isim_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.log_isim_2.setMinimumSize(QtCore.QSize(110, 36))
        self.log_isim_2.setMaximumSize(QtCore.QSize(65, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.log_isim_2.setFont(font)
        self.log_isim_2.setObjectName("log_isim_2")
        self.gridLayout.addWidget(self.log_isim_2, 0, 3, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 1, 3, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout.addWidget(self.comboBox_2, 2, 3, 1, 1)
        self.comboBox_8 = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_8.setFont(font)
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.gridLayout.addWidget(self.comboBox_8, 8, 3, 1, 1)
        self.comboBox_13 = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_13.setFont(font)
        self.comboBox_13.setObjectName("comboBox_13")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.gridLayout.addWidget(self.comboBox_13, 13, 3, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.gridLayout.addWidget(self.comboBox_3, 3, 3, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_4.setFont(font)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.gridLayout.addWidget(self.comboBox_4, 4, 3, 1, 1)
        self.comboBox_5 = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_5.setFont(font)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.gridLayout.addWidget(self.comboBox_5, 5, 3, 1, 1)
        self.comboBox_7 = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_7.setFont(font)
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.gridLayout.addWidget(self.comboBox_7, 7, 3, 1, 1)
        self.comboBox_6 = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_6.setFont(font)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.gridLayout.addWidget(self.comboBox_6, 6, 3, 1, 1)
        self.comboBox_9 = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_9.setFont(font)
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.gridLayout.addWidget(self.comboBox_9, 9, 3, 1, 1)
        self.comboBox_10 = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_10.setFont(font)
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.gridLayout.addWidget(self.comboBox_10, 10, 3, 1, 1)
        self.comboBox_19 = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_19.setFont(font)
        self.comboBox_19.setObjectName("comboBox_19")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.gridLayout.addWidget(self.comboBox_19, 19, 3, 1, 1)
        self.comboBox_11 = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_11.setFont(font)
        self.comboBox_11.setObjectName("comboBox_11")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.gridLayout.addWidget(self.comboBox_11, 11, 3, 1, 1)
        self.comboBox_14 = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_14.setFont(font)
        self.comboBox_14.setObjectName("comboBox_14")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.gridLayout.addWidget(self.comboBox_14, 14, 3, 1, 1)
        self.comboBox_12 = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_12.setFont(font)
        self.comboBox_12.setObjectName("comboBox_12")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.gridLayout.addWidget(self.comboBox_12, 12, 3, 1, 1)
        self.comboBox_17 = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_17.setFont(font)
        self.comboBox_17.setObjectName("comboBox_17")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.gridLayout.addWidget(self.comboBox_17, 17, 3, 1, 1)
        self.comboBox_16 = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_16.setFont(font)
        self.comboBox_16.setObjectName("comboBox_16")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.gridLayout.addWidget(self.comboBox_16, 16, 3, 1, 1)
        self.comboBox_18 = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_18.setFont(font)
        self.comboBox_18.setObjectName("comboBox_18")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.gridLayout.addWidget(self.comboBox_18, 18, 3, 1, 1)
        self.comboBox_15 = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_15.setFont(font)
        self.comboBox_15.setObjectName("comboBox_15")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.gridLayout.addWidget(self.comboBox_15, 15, 3, 1, 1)
        self.comboBox_20 = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_20.setFont(font)
        self.comboBox_20.setObjectName("comboBox_20")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.gridLayout.addWidget(self.comboBox_20, 20, 3, 1, 1)
        self.log_isim = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.log_isim.setMinimumSize(QtCore.QSize(65, 36))
        self.log_isim.setMaximumSize(QtCore.QSize(65, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.log_isim.setFont(font)
        self.log_isim.setObjectName("log_isim")
        self.gridLayout.addWidget(self.log_isim, 0, 4, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.save = QtWidgets.QPushButton(Widget)
        self.save.setGeometry(QtCore.QRect(530, 580, 111, 51))
        self.save.setObjectName("save")
        self.frame = QtWidgets.QFrame(Widget)
        self.frame.setGeometry(QtCore.QRect(260, 590, 111, 51))
        self.frame.setStyleSheet("background-color: rgb(216, 0, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.stop = QtWidgets.QPushButton(self.frame)
        self.stop.setGeometry(QtCore.QRect(0, 0, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.stop.setFont(font)
        self.stop.setStyleSheet("border-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 0, 0, 255), stop:0.479904 rgba(255, 0, 0, 255), stop:0.522685 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));")
        self.stop.setObjectName("stop")
        self.frame_2 = QtWidgets.QFrame(Widget)
        self.frame_2.setGeometry(QtCore.QRect(20, 590, 111, 51))
        self.frame_2.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.farm1 = QtWidgets.QPushButton(self.frame_2)
        self.farm1.setGeometry(QtCore.QRect(0, 0, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.farm1.setFont(font)
        self.farm1.setMouseTracking(True)
        self.farm1.setStyleSheet("border-color: rgb(0, 255, 0);\n"
"border-left-color: rgb(170, 255, 0);")
        self.farm1.setObjectName("farm1")
        self.frame_3 = QtWidgets.QFrame(Widget)
        self.frame_3.setGeometry(QtCore.QRect(140, 590, 111, 51))
        self.frame_3.setStyleSheet("background-color: rgb(201, 204, 2);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.farm2 = QtWidgets.QPushButton(self.frame_3)
        self.farm2.setGeometry(QtCore.QRect(0, 0, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.farm2.setFont(font)
        self.farm2.setMouseTracking(True)
        self.farm2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.farm2.setStyleSheet("gridline-color: rgb(255, 0, 0);")
        self.farm2.setObjectName("farm2")

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.sira_13.setText(_translate("Widget", "13"))
        self.sira_20.setText(_translate("Widget", "20"))
        self.sira_7.setText(_translate("Widget", "7"))
        self.sifre_isim.setText(_translate("Widget", "Pass"))
        self.email_isim.setText(_translate("Widget", "E-mail"))
        self.sira_5.setText(_translate("Widget", "5"))
        self.sira_11.setText(_translate("Widget", "11"))
        self.sira_8.setText(_translate("Widget", "8"))
        self.sira_4.setText(_translate("Widget", "4"))
        self.sira_14.setText(_translate("Widget", "14"))
        self.sira_9.setText(_translate("Widget", "9"))
        self.sira_19.setText(_translate("Widget", "19"))
        self.sira_16.setText(_translate("Widget", "16"))
        self.sira_12.setText(_translate("Widget", "12"))
        self.sira_17.setText(_translate("Widget", "17"))
        self.lastlogin.setText(_translate("Widget", "Last Login: "))
        self.gold.setText(_translate("Widget", "Picture"))
        self.sira_10.setText(_translate("Widget", "10"))
        self.sira_6.setText(_translate("Widget", "6"))
        self.sira_3.setText(_translate("Widget", "3"))
        self.sira.setText(_translate("Widget", "1"))
        self.sira_15.setText(_translate("Widget", "15"))
        self.lastlogin_2.setText(_translate("Widget", "Last Login: "))
        self.gold_2.setText(_translate("Widget", "Picture"))
        self.sira_18.setText(_translate("Widget", "18"))
        self.gold_3.setText(_translate("Widget", "Picture"))
        self.lastlogin_3.setText(_translate("Widget", "Last Login: "))
        self.sira_isim.setText(_translate("Widget", "Index"))
        self.sira_2.setText(_translate("Widget", "2"))
        self.lastlogin_4.setText(_translate("Widget", "Last Login: "))
        self.gold_4.setText(_translate("Widget", "Picture"))
        self.gold_13.setText(_translate("Widget", "Picture"))
        self.lastlogin_13.setText(_translate("Widget", "Last Login: "))
        self.lastlogin_9.setText(_translate("Widget", "Last Login: "))
        self.gold_9.setText(_translate("Widget", "Picture"))
        self.gold_7.setText(_translate("Widget", "Picture"))
        self.lastlogin_7.setText(_translate("Widget", "Last Login: "))
        self.lastlogin_10.setText(_translate("Widget", "Last Login: "))
        self.gold_10.setText(_translate("Widget", "Picture"))
        self.gold_11.setText(_translate("Widget", "Picture"))
        self.lastlogin_11.setText(_translate("Widget", "Last Login: "))
        self.gold_5.setText(_translate("Widget", "Picture"))
        self.lastlogin_5.setText(_translate("Widget", "Last Login: "))
        self.gold_12.setText(_translate("Widget", "Picture"))
        self.lastlogin_12.setText(_translate("Widget", "Last Login: "))
        self.lastlogin_14.setText(_translate("Widget", "Last Login: "))
        self.gold_14.setText(_translate("Widget", "Picture"))
        self.gold_6.setText(_translate("Widget", "Picture"))
        self.lastlogin_6.setText(_translate("Widget", "Last Login: "))
        self.gold_15.setText(_translate("Widget", "Picture"))
        self.lastlogin_15.setText(_translate("Widget", "Last Login: "))
        self.lastlogin_8.setText(_translate("Widget", "Last Login: "))
        self.gold_8.setText(_translate("Widget", "Picture"))
        self.gold_16.setText(_translate("Widget", "Picture"))
        self.lastlogin_16.setText(_translate("Widget", "Last Login: "))
        self.gold_20.setText(_translate("Widget", "Picture"))
        self.lastlogin_20.setText(_translate("Widget", "Last Login: "))
        self.lastlogin_18.setText(_translate("Widget", "Last Login: "))
        self.gold_18.setText(_translate("Widget", "Picture"))
        self.lastlogin_19.setText(_translate("Widget", "Last Login: "))
        self.gold_19.setText(_translate("Widget", "Picture"))
        self.lastlogin_17.setText(_translate("Widget", "Last Login: "))
        self.gold_17.setText(_translate("Widget", "Picture"))
        self.log_isim_2.setText(_translate("Widget", "Farm Type"))
        self.comboBox.setItemText(0, _translate("Widget", "Farm"))
        self.comboBox.setItemText(1, _translate("Widget", "Sawmill"))
        self.comboBox.setItemText(2, _translate("Widget", "Quartz"))
        self.comboBox.setItemText(3, _translate("Widget", "Iron"))
        self.comboBox_2.setItemText(0, _translate("Widget", "Farm"))
        self.comboBox_2.setItemText(1, _translate("Widget", "Sawmill"))
        self.comboBox_2.setItemText(2, _translate("Widget", "Quartz"))
        self.comboBox_2.setItemText(3, _translate("Widget", "Iron"))
        self.comboBox_8.setItemText(0, _translate("Widget", "Farm"))
        self.comboBox_8.setItemText(1, _translate("Widget", "Sawmill"))
        self.comboBox_8.setItemText(2, _translate("Widget", "Quartz"))
        self.comboBox_8.setItemText(3, _translate("Widget", "Iron"))
        self.comboBox_13.setItemText(0, _translate("Widget", "Farm"))
        self.comboBox_13.setItemText(1, _translate("Widget", "Sawmill"))
        self.comboBox_13.setItemText(2, _translate("Widget", "Quartz"))
        self.comboBox_13.setItemText(3, _translate("Widget", "Iron"))
        self.comboBox_3.setItemText(0, _translate("Widget", "Farm"))
        self.comboBox_3.setItemText(1, _translate("Widget", "Sawmill"))
        self.comboBox_3.setItemText(2, _translate("Widget", "Quartz"))
        self.comboBox_3.setItemText(3, _translate("Widget", "Iron"))
        self.comboBox_4.setItemText(0, _translate("Widget", "Farm"))
        self.comboBox_4.setItemText(1, _translate("Widget", "Sawmill"))
        self.comboBox_4.setItemText(2, _translate("Widget", "Quartz"))
        self.comboBox_4.setItemText(3, _translate("Widget", "Iron"))
        self.comboBox_5.setItemText(0, _translate("Widget", "Farm"))
        self.comboBox_5.setItemText(1, _translate("Widget", "Sawmill"))
        self.comboBox_5.setItemText(2, _translate("Widget", "Quartz"))
        self.comboBox_5.setItemText(3, _translate("Widget", "Iron"))
        self.comboBox_7.setItemText(0, _translate("Widget", "Farm"))
        self.comboBox_7.setItemText(1, _translate("Widget", "Sawmill"))
        self.comboBox_7.setItemText(2, _translate("Widget", "Quartz"))
        self.comboBox_7.setItemText(3, _translate("Widget", "Iron"))
        self.comboBox_6.setItemText(0, _translate("Widget", "Farm"))
        self.comboBox_6.setItemText(1, _translate("Widget", "Sawmill"))
        self.comboBox_6.setItemText(2, _translate("Widget", "Quartz"))
        self.comboBox_6.setItemText(3, _translate("Widget", "Iron"))
        self.comboBox_9.setItemText(0, _translate("Widget", "Farm"))
        self.comboBox_9.setItemText(1, _translate("Widget", "Sawmill"))
        self.comboBox_9.setItemText(2, _translate("Widget", "Quartz"))
        self.comboBox_9.setItemText(3, _translate("Widget", "Iron"))
        self.comboBox_10.setItemText(0, _translate("Widget", "Farm"))
        self.comboBox_10.setItemText(1, _translate("Widget", "Sawmill"))
        self.comboBox_10.setItemText(2, _translate("Widget", "Quartz"))
        self.comboBox_10.setItemText(3, _translate("Widget", "Iron"))
        self.comboBox_19.setItemText(0, _translate("Widget", "Farm"))
        self.comboBox_19.setItemText(1, _translate("Widget", "Sawmill"))
        self.comboBox_19.setItemText(2, _translate("Widget", "Quartz"))
        self.comboBox_19.setItemText(3, _translate("Widget", "Iron"))
        self.comboBox_11.setItemText(0, _translate("Widget", "Farm"))
        self.comboBox_11.setItemText(1, _translate("Widget", "Sawmill"))
        self.comboBox_11.setItemText(2, _translate("Widget", "Quartz"))
        self.comboBox_11.setItemText(3, _translate("Widget", "Iron"))
        self.comboBox_14.setItemText(0, _translate("Widget", "Farm"))
        self.comboBox_14.setItemText(1, _translate("Widget", "Sawmill"))
        self.comboBox_14.setItemText(2, _translate("Widget", "Quartz"))
        self.comboBox_14.setItemText(3, _translate("Widget", "Iron"))
        self.comboBox_12.setItemText(0, _translate("Widget", "Farm"))
        self.comboBox_12.setItemText(1, _translate("Widget", "Sawmill"))
        self.comboBox_12.setItemText(2, _translate("Widget", "Quartz"))
        self.comboBox_12.setItemText(3, _translate("Widget", "Iron"))
        self.comboBox_17.setItemText(0, _translate("Widget", "Farm"))
        self.comboBox_17.setItemText(1, _translate("Widget", "Sawmill"))
        self.comboBox_17.setItemText(2, _translate("Widget", "Quartz"))
        self.comboBox_17.setItemText(3, _translate("Widget", "Iron"))
        self.comboBox_16.setItemText(0, _translate("Widget", "Farm"))
        self.comboBox_16.setItemText(1, _translate("Widget", "Sawmill"))
        self.comboBox_16.setItemText(2, _translate("Widget", "Quartz"))
        self.comboBox_16.setItemText(3, _translate("Widget", "Iron"))
        self.comboBox_18.setItemText(0, _translate("Widget", "Farm"))
        self.comboBox_18.setItemText(1, _translate("Widget", "Sawmill"))
        self.comboBox_18.setItemText(2, _translate("Widget", "Quartz"))
        self.comboBox_18.setItemText(3, _translate("Widget", "Iron"))
        self.comboBox_15.setItemText(0, _translate("Widget", "Farm"))
        self.comboBox_15.setItemText(1, _translate("Widget", "Sawmill"))
        self.comboBox_15.setItemText(2, _translate("Widget", "Quartz"))
        self.comboBox_15.setItemText(3, _translate("Widget", "Iron"))
        self.comboBox_20.setItemText(0, _translate("Widget", "Farm"))
        self.comboBox_20.setItemText(1, _translate("Widget", "Sawmill"))
        self.comboBox_20.setItemText(2, _translate("Widget", "Quartz"))
        self.comboBox_20.setItemText(3, _translate("Widget", "Iron"))
        self.log_isim.setText(_translate("Widget", "LOG"))
        self.save.setText(_translate("Widget", "Save"))
        self.stop.setText(_translate("Widget", "Stop"))
        self.farm1.setText(_translate("Widget", "Farm 1"))
        self.farm2.setText(_translate("Widget", "Farm 2"))

