# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/masaüstü/yazılımileilgilihersey/onluk/osmanli oyun bot/yeni versiyon/BOT-GUI/BOT/BOT-GUI/botbaslat.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow3(object):
    def setupUi(self, MainWindow3):
        MainWindow3.setObjectName("MainWindow3")
        MainWindow3.resize(603, 691)
        MainWindow3.setStyleSheet("selection-color: rgb(0, 0, 0);\n"
"background-color: rgb(245, 245, 245);\n"
"alternate-background-color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(0, 0, 100);\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow3)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 601, 561))
        self.scrollArea.setStyleSheet("color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"selection-color: rgb(170, 170, 255);\n"
"border-top-color: rgb(255, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 599, 559))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.scrollAreaWidgetContents)
        self.scrollArea_2.setGeometry(QtCore.QRect(0, 0, 601, 561))
        self.scrollArea_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"selection-color: rgb(255, 255, 255);\n"
"border-top-color: rgb(255, 255, 255);n"
"background-color:  rgb(255,255,255);")
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 598, 647))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.line_84 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_84.setMinimumSize(QtCore.QSize(5, 5))
        self.line_84.setSizeIncrement(QtCore.QSize(50, 50))
        self.line_84.setBaseSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.line_84.setFont(font)
        self.line_84.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.line_84.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_84.setLineWidth(6)
        self.line_84.setMidLineWidth(0)
        self.line_84.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_84.setObjectName("line_84")
        self.gridLayout_2.addWidget(self.line_84, 2, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.line_49 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_49.setMinimumSize(QtCore.QSize(5, 5))
        self.line_49.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_49.setLineWidth(6)
        self.line_49.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_49.setObjectName("line_49")
        self.gridLayout.addWidget(self.line_49, 15, 3, 1, 1)
        self.line_52 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_52.setMinimumSize(QtCore.QSize(5, 5))
        self.line_52.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_52.setLineWidth(6)
        self.line_52.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_52.setObjectName("line_52")
        self.gridLayout.addWidget(self.line_52, 13, 1, 1, 1)
        self.line_48 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_48.setMinimumSize(QtCore.QSize(5, 5))
        self.line_48.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_48.setLineWidth(6)
        self.line_48.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_48.setObjectName("line_48")
        self.gridLayout.addWidget(self.line_48, 13, 3, 1, 1)
        self.line_45 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_45.setMinimumSize(QtCore.QSize(5, 5))
        self.line_45.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_45.setLineWidth(6)
        self.line_45.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_45.setObjectName("line_45")
        self.gridLayout.addWidget(self.line_45, 6, 3, 1, 1)
        self.line_47 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_47.setMinimumSize(QtCore.QSize(5, 5))
        self.line_47.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_47.setLineWidth(6)
        self.line_47.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_47.setObjectName("line_47")
        self.gridLayout.addWidget(self.line_47, 11, 3, 1, 1)
        self.lastlogin_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.lastlogin_4.setMinimumSize(QtCore.QSize(75, 41))
        self.lastlogin_4.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lastlogin_4.setFont(font)
        self.lastlogin_4.setText("")
        self.lastlogin_4.setObjectName("lastlogin_4")
        self.gridLayout.addWidget(self.lastlogin_4, 9, 6, 1, 1)
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.gold_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.gold_6.setMinimumSize(QtCore.QSize(350, 25))
        self.gold_6.setMaximumSize(QtCore.QSize(131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gold_6.setFont(font)
        self.gold_6.setText("")
        self.gold_6.setObjectName("gold_6")
        self.gridLayout_14.addWidget(self.gold_6, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_14, 13, 4, 1, 1)
        self.sira_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.sira_10.setMinimumSize(QtCore.QSize(25, 36))
        self.sira_10.setMaximumSize(QtCore.QSize(25, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sira_10.setFont(font)
        self.sira_10.setObjectName("sira_10")
        self.gridLayout.addWidget(self.sira_10, 21, 0, 1, 1)
        self.sira_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.sira_9.setMinimumSize(QtCore.QSize(25, 36))
        self.sira_9.setMaximumSize(QtCore.QSize(25, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sira_9.setFont(font)
        self.sira_9.setObjectName("sira_9")
        self.gridLayout.addWidget(self.sira_9, 19, 0, 1, 1)
        self.sira_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.sira_4.setMinimumSize(QtCore.QSize(25, 36))
        self.sira_4.setMaximumSize(QtCore.QSize(25, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sira_4.setFont(font)
        self.sira_4.setObjectName("sira_4")
        self.gridLayout.addWidget(self.sira_4, 9, 0, 1, 1)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gold = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.gold.setMinimumSize(QtCore.QSize(350, 25))
        self.gold.setMaximumSize(QtCore.QSize(131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gold.setFont(font)
        self.gold.setText("")
        self.gold.setObjectName("gold")
        self.gridLayout_8.addWidget(self.gold, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_8, 2, 4, 1, 1)
        self.line_51 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_51.setMinimumSize(QtCore.QSize(5, 5))
        self.line_51.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_51.setLineWidth(6)
        self.line_51.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_51.setObjectName("line_51")
        self.gridLayout.addWidget(self.line_51, 15, 1, 1, 1)
        self.line_54 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_54.setMinimumSize(QtCore.QSize(5, 5))
        self.line_54.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_54.setLineWidth(6)
        self.line_54.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_54.setObjectName("line_54")
        self.gridLayout.addWidget(self.line_54, 11, 1, 1, 1)
        self.line_53 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_53.setMinimumSize(QtCore.QSize(5, 5))
        self.line_53.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_53.setLineWidth(6)
        self.line_53.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_53.setObjectName("line_53")
        self.gridLayout.addWidget(self.line_53, 9, 1, 1, 1)
        self.sira_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.sira_5.setMinimumSize(QtCore.QSize(25, 36))
        self.sira_5.setMaximumSize(QtCore.QSize(25, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sira_5.setFont(font)
        self.sira_5.setObjectName("sira_5")
        self.gridLayout.addWidget(self.sira_5, 11, 0, 1, 1)
        self.sira_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.sira_8.setMinimumSize(QtCore.QSize(25, 36))
        self.sira_8.setMaximumSize(QtCore.QSize(25, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sira_8.setFont(font)
        self.sira_8.setObjectName("sira_8")
        self.gridLayout.addWidget(self.sira_8, 17, 0, 1, 1)
        self.line_50 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_50.setMinimumSize(QtCore.QSize(5, 5))
        self.line_50.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_50.setLineWidth(6)
        self.line_50.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_50.setObjectName("line_50")
        self.gridLayout.addWidget(self.line_50, 17, 3, 1, 1)
        self.sira_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.sira_7.setMinimumSize(QtCore.QSize(25, 36))
        self.sira_7.setMaximumSize(QtCore.QSize(25, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sira_7.setFont(font)
        self.sira_7.setObjectName("sira_7")
        self.gridLayout.addWidget(self.sira_7, 15, 0, 1, 1)
        self.sira_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.sira_6.setMinimumSize(QtCore.QSize(25, 36))
        self.sira_6.setMaximumSize(QtCore.QSize(25, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sira_6.setFont(font)
        self.sira_6.setObjectName("sira_6")
        self.gridLayout.addWidget(self.sira_6, 13, 0, 1, 1)
        self.gridLayout_16 = QtWidgets.QGridLayout()
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.gold_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.gold_8.setMinimumSize(QtCore.QSize(350, 25))
        self.gold_8.setMaximumSize(QtCore.QSize(131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gold_8.setFont(font)
        self.gold_8.setText("")
        self.gold_8.setObjectName("gold_8")
        self.gridLayout_16.addWidget(self.gold_8, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_16, 17, 4, 1, 1)
        self.sira_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.sira_2.setMinimumSize(QtCore.QSize(25, 36))
        self.sira_2.setMaximumSize(QtCore.QSize(25, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sira_2.setFont(font)
        self.sira_2.setObjectName("sira_2")
        self.gridLayout.addWidget(self.sira_2, 4, 0, 1, 1)
        self.lastlogin_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.lastlogin_7.setMinimumSize(QtCore.QSize(75, 41))
        self.lastlogin_7.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lastlogin_7.setFont(font)
        self.lastlogin_7.setText("")
        self.lastlogin_7.setObjectName("lastlogin_7")
        self.gridLayout.addWidget(self.lastlogin_7, 15, 6, 1, 1)
        self.sira = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.sira.setMinimumSize(QtCore.QSize(25, 36))
        self.sira.setMaximumSize(QtCore.QSize(25, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sira.setFont(font)
        self.sira.setObjectName("sira")
        self.gridLayout.addWidget(self.sira, 2, 0, 1, 1)
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.gold_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.gold_4.setMinimumSize(QtCore.QSize(350, 25))
        self.gold_4.setMaximumSize(QtCore.QSize(131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gold_4.setFont(font)
        self.gold_4.setText("")
        self.gold_4.setObjectName("gold_4")
        self.gridLayout_12.addWidget(self.gold_4, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_12, 9, 4, 1, 1)
        self.sira_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.sira_3.setMinimumSize(QtCore.QSize(25, 36))
        self.sira_3.setMaximumSize(QtCore.QSize(25, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sira_3.setFont(font)
        self.sira_3.setObjectName("sira_3")
        self.gridLayout.addWidget(self.sira_3, 6, 0, 1, 1)
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.gold_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.gold_3.setMinimumSize(QtCore.QSize(350, 25))
        self.gold_3.setMaximumSize(QtCore.QSize(131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gold_3.setFont(font)
        self.gold_3.setText("")
        self.gold_3.setObjectName("gold_3")
        self.gridLayout_11.addWidget(self.gold_3, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_11, 6, 4, 1, 1)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gold_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.gold_2.setMinimumSize(QtCore.QSize(350, 25))
        self.gold_2.setMaximumSize(QtCore.QSize(131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gold_2.setFont(font)
        self.gold_2.setText("")
        self.gold_2.setObjectName("gold_2")
        self.gridLayout_10.addWidget(self.gold_2, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_10, 4, 4, 1, 1)
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.gold_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.gold_7.setMinimumSize(QtCore.QSize(350, 25))
        self.gold_7.setMaximumSize(QtCore.QSize(131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gold_7.setFont(font)
        self.gold_7.setText("")
        self.gold_7.setObjectName("gold_7")
        self.gridLayout_15.addWidget(self.gold_7, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_15, 15, 4, 1, 1)
        self.lastlogin_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.lastlogin_8.setMinimumSize(QtCore.QSize(75, 41))
        self.lastlogin_8.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lastlogin_8.setFont(font)
        self.lastlogin_8.setText("")
        self.lastlogin_8.setObjectName("lastlogin_8")
        self.gridLayout.addWidget(self.lastlogin_8, 17, 6, 1, 1)
        self.gridLayout_17 = QtWidgets.QGridLayout()
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.gold_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.gold_9.setMinimumSize(QtCore.QSize(350, 25))
        self.gold_9.setMaximumSize(QtCore.QSize(131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gold_9.setFont(font)
        self.gold_9.setText("")
        self.gold_9.setObjectName("gold_9")
        self.gridLayout_17.addWidget(self.gold_9, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_17, 19, 4, 1, 1)
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.gold_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.gold_5.setMinimumSize(QtCore.QSize(350, 25))
        self.gold_5.setMaximumSize(QtCore.QSize(131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gold_5.setFont(font)
        self.gold_5.setText("")
        self.gold_5.setObjectName("gold_5")
        self.gridLayout_13.addWidget(self.gold_5, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_13, 11, 4, 1, 1)
        self.gridLayout_18 = QtWidgets.QGridLayout()
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.gold_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.gold_10.setMinimumSize(QtCore.QSize(350, 25))
        self.gold_10.setMaximumSize(QtCore.QSize(131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gold_10.setFont(font)
        self.gold_10.setText("")
        self.gold_10.setObjectName("gold_10")
        self.gridLayout_18.addWidget(self.gold_10, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_18, 21, 4, 1, 1)
        self.lastlogin_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.lastlogin_5.setMinimumSize(QtCore.QSize(75, 41))
        self.lastlogin_5.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lastlogin_5.setFont(font)
        self.lastlogin_5.setText("")
        self.lastlogin_5.setObjectName("lastlogin_5")
        self.gridLayout.addWidget(self.lastlogin_5, 11, 6, 1, 1)
        self.line_27 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_27.setMinimumSize(QtCore.QSize(5, 5))
        self.line_27.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_27.setLineWidth(6)
        self.line_27.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_27.setObjectName("line_27")
        self.gridLayout.addWidget(self.line_27, 17, 5, 1, 1)
        self.lastlogin = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.lastlogin.setMinimumSize(QtCore.QSize(75, 41))
        self.lastlogin.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lastlogin.setFont(font)
        self.lastlogin.setText("")
        self.lastlogin.setObjectName("lastlogin")
        self.gridLayout.addWidget(self.lastlogin, 2, 6, 1, 1)
        self.line_10 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_10.setMinimumSize(QtCore.QSize(5, 5))
        self.line_10.setSizeIncrement(QtCore.QSize(50, 50))
        self.line_10.setBaseSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.line_10.setFont(font)
        self.line_10.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.line_10.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_10.setLineWidth(6)
        self.line_10.setMidLineWidth(0)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setObjectName("line_10")
        self.gridLayout.addWidget(self.line_10, 20, 0, 1, 7)
        self.line_66 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_66.setMinimumSize(QtCore.QSize(5, 5))
        self.line_66.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_66.setLineWidth(6)
        self.line_66.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_66.setObjectName("line_66")
        self.gridLayout.addWidget(self.line_66, 21, 1, 1, 1)
        self.lastlogin_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.lastlogin_2.setMinimumSize(QtCore.QSize(75, 41))
        self.lastlogin_2.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lastlogin_2.setFont(font)
        self.lastlogin_2.setText("")
        self.lastlogin_2.setObjectName("lastlogin_2")
        self.gridLayout.addWidget(self.lastlogin_2, 4, 6, 1, 1)
        self.line_46 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_46.setMinimumSize(QtCore.QSize(5, 5))
        self.line_46.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_46.setLineWidth(6)
        self.line_46.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_46.setObjectName("line_46")
        self.gridLayout.addWidget(self.line_46, 9, 3, 1, 1)
        self.line_41 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_41.setMinimumSize(QtCore.QSize(5, 5))
        self.line_41.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_41.setLineWidth(6)
        self.line_41.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_41.setObjectName("line_41")
        self.gridLayout.addWidget(self.line_41, 2, 5, 1, 1)
        self.lastlogin_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.lastlogin_6.setMinimumSize(QtCore.QSize(75, 41))
        self.lastlogin_6.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lastlogin_6.setFont(font)
        self.lastlogin_6.setText("")
        self.lastlogin_6.setObjectName("lastlogin_6")
        self.gridLayout.addWidget(self.lastlogin_6, 13, 6, 1, 1)
        self.line_21 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_21.setMinimumSize(QtCore.QSize(5, 5))
        self.line_21.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_21.setLineWidth(6)
        self.line_21.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_21.setObjectName("line_21")
        self.gridLayout.addWidget(self.line_21, 4, 5, 1, 1)
        self.line_22 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_22.setMinimumSize(QtCore.QSize(5, 5))
        self.line_22.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_22.setLineWidth(6)
        self.line_22.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_22.setObjectName("line_22")
        self.gridLayout.addWidget(self.line_22, 6, 5, 1, 1)
        self.line_23 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_23.setMinimumSize(QtCore.QSize(5, 5))
        self.line_23.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_23.setLineWidth(6)
        self.line_23.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_23.setObjectName("line_23")
        self.gridLayout.addWidget(self.line_23, 9, 5, 1, 1)
        self.line_24 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_24.setMinimumSize(QtCore.QSize(5, 5))
        self.line_24.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_24.setLineWidth(6)
        self.line_24.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_24.setObjectName("line_24")
        self.gridLayout.addWidget(self.line_24, 11, 5, 1, 1)
        self.line_25 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_25.setMinimumSize(QtCore.QSize(5, 5))
        self.line_25.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_25.setLineWidth(6)
        self.line_25.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_25.setObjectName("line_25")
        self.gridLayout.addWidget(self.line_25, 13, 5, 1, 1)
        self.log_isim_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.log_isim_2.setMinimumSize(QtCore.QSize(75, 36))
        self.log_isim_2.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.log_isim_2.setFont(font)
        self.log_isim_2.setObjectName("log_isim_2")
        self.gridLayout.addWidget(self.log_isim_2, 0, 6, 1, 1)
        self.line_26 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_26.setMinimumSize(QtCore.QSize(5, 5))
        self.line_26.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_26.setLineWidth(6)
        self.line_26.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_26.setObjectName("line_26")
        self.gridLayout.addWidget(self.line_26, 15, 5, 1, 1)
        self.line_56 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_56.setMinimumSize(QtCore.QSize(5, 5))
        self.line_56.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_56.setLineWidth(6)
        self.line_56.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_56.setObjectName("line_56")
        self.gridLayout.addWidget(self.line_56, 4, 1, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_6.setMinimumSize(QtCore.QSize(5, 5))
        self.line_6.setSizeIncrement(QtCore.QSize(50, 50))
        self.line_6.setBaseSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.line_6.setFont(font)
        self.line_6.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.line_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_6.setLineWidth(6)
        self.line_6.setMidLineWidth(0)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setObjectName("line_6")
        self.gridLayout.addWidget(self.line_6, 12, 0, 1, 7)
        self.line_7 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_7.setMinimumSize(QtCore.QSize(5, 5))
        self.line_7.setSizeIncrement(QtCore.QSize(50, 50))
        self.line_7.setBaseSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.line_7.setFont(font)
        self.line_7.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.line_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_7.setLineWidth(6)
        self.line_7.setMidLineWidth(0)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setObjectName("line_7")
        self.gridLayout.addWidget(self.line_7, 14, 0, 1, 7)
        self.line_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_2.setMinimumSize(QtCore.QSize(5, 5))
        self.line_2.setSizeIncrement(QtCore.QSize(50, 50))
        self.line_2.setBaseSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.line_2.setFont(font)
        self.line_2.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setLineWidth(6)
        self.line_2.setMidLineWidth(0)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 1, 0, 1, 7)
        self.line_55 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_55.setMinimumSize(QtCore.QSize(5, 5))
        self.line_55.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_55.setLineWidth(6)
        self.line_55.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_55.setObjectName("line_55")
        self.gridLayout.addWidget(self.line_55, 6, 1, 1, 1)
        self.line_28 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_28.setMinimumSize(QtCore.QSize(5, 5))
        self.line_28.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_28.setLineWidth(6)
        self.line_28.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_28.setObjectName("line_28")
        self.gridLayout.addWidget(self.line_28, 19, 5, 1, 1)
        self.lastlogin_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.lastlogin_10.setMinimumSize(QtCore.QSize(75, 41))
        self.lastlogin_10.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lastlogin_10.setFont(font)
        self.lastlogin_10.setText("")
        self.lastlogin_10.setObjectName("lastlogin_10")
        self.gridLayout.addWidget(self.lastlogin_10, 21, 6, 1, 1)
        self.line_62 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_62.setMinimumSize(QtCore.QSize(5, 5))
        self.line_62.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_62.setLineWidth(6)
        self.line_62.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_62.setObjectName("line_62")
        self.gridLayout.addWidget(self.line_62, 21, 3, 1, 1)
        self.line_29 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_29.setMinimumSize(QtCore.QSize(5, 5))
        self.line_29.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_29.setLineWidth(6)
        self.line_29.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_29.setObjectName("line_29")
        self.gridLayout.addWidget(self.line_29, 21, 5, 1, 1)
        self.log_isim_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.log_isim_3.setMinimumSize(QtCore.QSize(65, 36))
        self.log_isim_3.setMaximumSize(QtCore.QSize(65, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.log_isim_3.setFont(font)
        self.log_isim_3.setObjectName("log_isim_3")
        self.gridLayout.addWidget(self.log_isim_3, 0, 2, 1, 1)
        self.line = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line.setMinimumSize(QtCore.QSize(5, 5))
        self.line.setSizeIncrement(QtCore.QSize(50, 50))
        self.line.setBaseSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.line.setFont(font)
        self.line.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(6)
        self.line.setMidLineWidth(0)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 3, 0, 1, 7)
        self.line_61 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_61.setMinimumSize(QtCore.QSize(5, 5))
        self.line_61.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_61.setLineWidth(6)
        self.line_61.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_61.setObjectName("line_61")
        self.gridLayout.addWidget(self.line_61, 19, 1, 1, 1)
        self.line_60 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_60.setMinimumSize(QtCore.QSize(5, 5))
        self.line_60.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_60.setLineWidth(6)
        self.line_60.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_60.setObjectName("line_60")
        self.gridLayout.addWidget(self.line_60, 19, 3, 1, 1)
        self.line_43 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_43.setMinimumSize(QtCore.QSize(5, 5))
        self.line_43.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_43.setLineWidth(6)
        self.line_43.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_43.setObjectName("line_43")
        self.gridLayout.addWidget(self.line_43, 2, 3, 1, 1)
        self.lastlogin_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.lastlogin_9.setMinimumSize(QtCore.QSize(75, 41))
        self.lastlogin_9.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lastlogin_9.setFont(font)
        self.lastlogin_9.setText("")
        self.lastlogin_9.setObjectName("lastlogin_9")
        self.gridLayout.addWidget(self.lastlogin_9, 19, 6, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_3.setMinimumSize(QtCore.QSize(5, 5))
        self.line_3.setSizeIncrement(QtCore.QSize(50, 50))
        self.line_3.setBaseSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.line_3.setFont(font)
        self.line_3.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.line_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_3.setLineWidth(6)
        self.line_3.setMidLineWidth(0)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 5, 0, 1, 7)
        self.line_5 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_5.setMinimumSize(QtCore.QSize(5, 5))
        self.line_5.setSizeIncrement(QtCore.QSize(50, 50))
        self.line_5.setBaseSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.line_5.setFont(font)
        self.line_5.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.line_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_5.setLineWidth(6)
        self.line_5.setMidLineWidth(0)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setObjectName("line_5")
        self.gridLayout.addWidget(self.line_5, 10, 0, 1, 7)
        self.line_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_4.setMinimumSize(QtCore.QSize(5, 5))
        self.line_4.setSizeIncrement(QtCore.QSize(50, 50))
        self.line_4.setBaseSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.line_4.setFont(font)
        self.line_4.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.line_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_4.setLineWidth(6)
        self.line_4.setMidLineWidth(0)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 7, 0, 1, 7)
        self.line_42 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_42.setMinimumSize(QtCore.QSize(5, 5))
        self.line_42.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_42.setLineWidth(6)
        self.line_42.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_42.setObjectName("line_42")
        self.gridLayout.addWidget(self.line_42, 0, 3, 1, 1)
        self.line_58 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_58.setMinimumSize(QtCore.QSize(5, 5))
        self.line_58.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_58.setLineWidth(6)
        self.line_58.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_58.setObjectName("line_58")
        self.gridLayout.addWidget(self.line_58, 0, 1, 1, 1)
        self.line_40 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_40.setMinimumSize(QtCore.QSize(5, 5))
        self.line_40.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_40.setLineWidth(6)
        self.line_40.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_40.setObjectName("line_40")
        self.gridLayout.addWidget(self.line_40, 0, 5, 1, 1)
        self.log_isim = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.log_isim.setMinimumSize(QtCore.QSize(350, 36))
        self.log_isim.setMaximumSize(QtCore.QSize(65, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.log_isim.setFont(font)
        self.log_isim.setObjectName("log_isim")
        self.gridLayout.addWidget(self.log_isim, 0, 4, 1, 1)
        self.line_59 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_59.setMinimumSize(QtCore.QSize(5, 5))
        self.line_59.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_59.setLineWidth(6)
        self.line_59.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_59.setObjectName("line_59")
        self.gridLayout.addWidget(self.line_59, 17, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.comboBox.setMaximumSize(QtCore.QSize(80, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 2, 2, 1, 1)
        self.line_9 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_9.setMinimumSize(QtCore.QSize(5, 5))
        self.line_9.setSizeIncrement(QtCore.QSize(50, 50))
        self.line_9.setBaseSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.line_9.setFont(font)
        self.line_9.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.line_9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_9.setLineWidth(6)
        self.line_9.setMidLineWidth(0)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setObjectName("line_9")
        self.gridLayout.addWidget(self.line_9, 18, 0, 1, 7)
        self.line_57 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_57.setMinimumSize(QtCore.QSize(5, 5))
        self.line_57.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_57.setLineWidth(6)
        self.line_57.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_57.setObjectName("line_57")
        self.gridLayout.addWidget(self.line_57, 2, 1, 1, 1)
        self.line_8 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_8.setMinimumSize(QtCore.QSize(5, 5))
        self.line_8.setSizeIncrement(QtCore.QSize(50, 50))
        self.line_8.setBaseSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.line_8.setFont(font)
        self.line_8.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.line_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_8.setLineWidth(6)
        self.line_8.setMidLineWidth(0)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setObjectName("line_8")
        self.gridLayout.addWidget(self.line_8, 16, 0, 1, 7)
        self.line_44 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_44.setMinimumSize(QtCore.QSize(5, 5))
        self.line_44.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_44.setLineWidth(6)
        self.line_44.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_44.setObjectName("line_44")
        self.gridLayout.addWidget(self.line_44, 4, 3, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.comboBox_2.setMaximumSize(QtCore.QSize(80, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout.addWidget(self.comboBox_2, 4, 2, 1, 1)
        self.lastlogin_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.lastlogin_3.setMinimumSize(QtCore.QSize(75, 41))
        self.lastlogin_3.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lastlogin_3.setFont(font)
        self.lastlogin_3.setText("")
        self.lastlogin_3.setObjectName("lastlogin_3")
        self.gridLayout.addWidget(self.lastlogin_3, 6, 6, 1, 1)
        self.comboBox_9 = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.comboBox_9.setMaximumSize(QtCore.QSize(80, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_9.setFont(font)
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.gridLayout.addWidget(self.comboBox_9, 19, 2, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.comboBox_3.setMaximumSize(QtCore.QSize(80, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.gridLayout.addWidget(self.comboBox_3, 6, 2, 1, 1)
        self.comboBox_7 = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.comboBox_7.setMaximumSize(QtCore.QSize(80, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_7.setFont(font)
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.gridLayout.addWidget(self.comboBox_7, 15, 2, 1, 1)
        self.comboBox_6 = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.comboBox_6.setMaximumSize(QtCore.QSize(80, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_6.setFont(font)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.gridLayout.addWidget(self.comboBox_6, 13, 2, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.comboBox_4.setMaximumSize(QtCore.QSize(80, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_4.setFont(font)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.gridLayout.addWidget(self.comboBox_4, 9, 2, 1, 1)
        self.comboBox_8 = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.comboBox_8.setMaximumSize(QtCore.QSize(80, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_8.setFont(font)
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.gridLayout.addWidget(self.comboBox_8, 17, 2, 1, 1)
        self.comboBox_5 = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.comboBox_5.setMaximumSize(QtCore.QSize(80, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_5.setFont(font)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.gridLayout.addWidget(self.comboBox_5, 11, 2, 1, 1)
        self.comboBox_10 = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.comboBox_10.setMaximumSize(QtCore.QSize(80, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_10.setFont(font)
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.gridLayout.addWidget(self.comboBox_10, 21, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 610, 111, 51))
        self.frame_2.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.farm1 = QtWidgets.QPushButton(self.frame_2)
        self.farm1.setGeometry(QtCore.QRect(0, 0, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.farm1.setFont(font)
        self.farm1.setMouseTracking(True)
        self.farm1.setStyleSheet("border-color: rgb(0, 255, 0);\n"
"border-left-color: rgb(170, 255, 0);")
        self.farm1.setObjectName("farm1")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(120, 610, 111, 51))
        self.frame_3.setStyleSheet("background-color: rgb(201, 204, 2);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.farm2 = QtWidgets.QPushButton(self.frame_3)
        self.farm2.setGeometry(QtCore.QRect(0, 0, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.farm2.setFont(font)
        self.farm2.setMouseTracking(True)
        self.farm2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.farm2.setStyleSheet("gridline-color: rgb(255, 0, 0);")
        self.farm2.setObjectName("farm2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(250, 610, 111, 51))
        self.frame.setStyleSheet("background-color: rgb(216, 0, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.stop = QtWidgets.QPushButton(self.frame)
        self.stop.setGeometry(QtCore.QRect(0, 0, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.stop.setFont(font)
        self.stop.setStyleSheet("border-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 0, 0, 255), stop:0.479904 rgba(255, 0, 0, 255), stop:0.522685 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));")
        self.stop.setObjectName("stop")
        MainWindow3.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(MainWindow3)
        self.toolBar.setObjectName("toolBar")
        MainWindow3.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionGiri = QtWidgets.QAction(MainWindow3)
        self.actionGiri.setObjectName("actionGiri")
        self.actionHesaplar_Ekle = QtWidgets.QAction(MainWindow3)
        self.actionHesaplar_Ekle.setObjectName("actionHesaplar_Ekle")
        self.actionBot_Ba_lar = QtWidgets.QAction(MainWindow3)
        self.actionBot_Ba_lar.setObjectName("actionBot_Ba_lar")
        self.actionBot_Ba_lat = QtWidgets.QAction(MainWindow3)
        self.actionBot_Ba_lat.setObjectName("actionBot_Ba_lat")
        self.actionHesap_Ekle = QtWidgets.QAction(MainWindow3)
        self.actionHesap_Ekle.setObjectName("actionHesap_Ekle")
        self.actionGiri_2 = QtWidgets.QAction(MainWindow3)
        self.actionGiri_2.setObjectName("actionGiri_2")
        self.toolBar.addAction(self.actionGiri_2)
        self.toolBar.addAction(self.actionHesap_Ekle)
        self.toolBar.addAction(self.actionBot_Ba_lat)

        self.retranslateUi(MainWindow3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow3)

    def retranslateUi(self, MainWindow3):
        _translate = QtCore.QCoreApplication.translate
        MainWindow3.setWindowTitle(_translate("MainWindow3", "MainWindow"))
        self.sira_10.setText(_translate("MainWindow3", "10"))
        self.sira_9.setText(_translate("MainWindow3", "9"))
        self.sira_4.setText(_translate("MainWindow3", "4"))
        self.sira_5.setText(_translate("MainWindow3", "5"))
        self.sira_8.setText(_translate("MainWindow3", "8"))
        self.sira_7.setText(_translate("MainWindow3", "7"))
        self.sira_6.setText(_translate("MainWindow3", "6"))
        self.sira_2.setText(_translate("MainWindow3", "2"))
        self.sira.setText(_translate("MainWindow3", "1"))
        self.sira_3.setText(_translate("MainWindow3", "3"))
        self.log_isim_2.setText(_translate("MainWindow3", "Time"))
        self.log_isim_3.setText(_translate("MainWindow3", "Farm"))
        self.log_isim.setText(_translate("MainWindow3", "U: -  kalan gün : - gün"))
        self.comboBox.setItemText(0, _translate("MainWindow3", "Tahıl"))
        self.comboBox.setItemText(1, _translate("MainWindow3", "Odun"))
        self.comboBox.setItemText(2, _translate("MainWindow3", "Kuvars"))
        self.comboBox.setItemText(3, _translate("MainWindow3", "Demir"))
        self.comboBox_2.setItemText(0, _translate("MainWindow3", "Tahıl"))
        self.comboBox_2.setItemText(1, _translate("MainWindow3", "Odun"))
        self.comboBox_2.setItemText(2, _translate("MainWindow3", "Kuvars"))
        self.comboBox_2.setItemText(3, _translate("MainWindow3", "Demir"))
        self.comboBox_9.setItemText(0, _translate("MainWindow3", "Tahıl"))
        self.comboBox_9.setItemText(1, _translate("MainWindow3", "Odun"))
        self.comboBox_9.setItemText(2, _translate("MainWindow3", "Kuvars"))
        self.comboBox_9.setItemText(3, _translate("MainWindow3", "Demir"))
        self.comboBox_3.setItemText(0, _translate("MainWindow3", "Tahıl"))
        self.comboBox_3.setItemText(1, _translate("MainWindow3", "Odun"))
        self.comboBox_3.setItemText(2, _translate("MainWindow3", "Kuvars"))
        self.comboBox_3.setItemText(3, _translate("MainWindow3", "Demir"))
        self.comboBox_7.setItemText(0, _translate("MainWindow3", "Tahıl"))
        self.comboBox_7.setItemText(1, _translate("MainWindow3", "Odun"))
        self.comboBox_7.setItemText(2, _translate("MainWindow3", "Kuvars"))
        self.comboBox_7.setItemText(3, _translate("MainWindow3", "Demir"))
        self.comboBox_6.setItemText(0, _translate("MainWindow3", "Tahıl"))
        self.comboBox_6.setItemText(1, _translate("MainWindow3", "Odun"))
        self.comboBox_6.setItemText(2, _translate("MainWindow3", "Kuvars"))
        self.comboBox_6.setItemText(3, _translate("MainWindow3", "Demir"))
        self.comboBox_4.setItemText(0, _translate("MainWindow3", "Tahıl"))
        self.comboBox_4.setItemText(1, _translate("MainWindow3", "Odun"))
        self.comboBox_4.setItemText(2, _translate("MainWindow3", "Kuvars"))
        self.comboBox_4.setItemText(3, _translate("MainWindow3", "Demir"))
        self.comboBox_8.setItemText(0, _translate("MainWindow3", "Tahıl"))
        self.comboBox_8.setItemText(1, _translate("MainWindow3", "Odun"))
        self.comboBox_8.setItemText(2, _translate("MainWindow3", "Kuvars"))
        self.comboBox_8.setItemText(3, _translate("MainWindow3", "Demir"))
        self.comboBox_5.setItemText(0, _translate("MainWindow3", "Tahıl"))
        self.comboBox_5.setItemText(1, _translate("MainWindow3", "Odun"))
        self.comboBox_5.setItemText(2, _translate("MainWindow3", "Kuvars"))
        self.comboBox_5.setItemText(3, _translate("MainWindow3", "Demir"))
        self.comboBox_10.setItemText(0, _translate("MainWindow3", "Tahıl"))
        self.comboBox_10.setItemText(1, _translate("MainWindow3", "Odun"))
        self.comboBox_10.setItemText(2, _translate("MainWindow3", "Kuvars"))
        self.comboBox_10.setItemText(3, _translate("MainWindow3", "Demir"))
        self.farm1.setText(_translate("MainWindow3", "Farm 1"))
        self.farm2.setText(_translate("MainWindow3", "Farm 2"))
        self.stop.setText(_translate("MainWindow3", "Stop"))
        self.toolBar.setWindowTitle(_translate("MainWindow3", "toolBar"))
        self.actionGiri.setText(_translate("MainWindow3", "Giriş"))
        self.actionHesaplar_Ekle.setText(_translate("MainWindow3", "Hesapları Ekle"))
        self.actionBot_Ba_lar.setText(_translate("MainWindow3", "Bot Başlat"))
        self.actionBot_Ba_lat.setText(_translate("MainWindow3", "Bot Başlat"))
        self.actionHesap_Ekle.setText(_translate("MainWindow3", "Hesap Ekle"))
        self.actionGiri_2.setText(_translate("MainWindow3", "Giriş"))

