# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/masaüstü/yazılımileilgilihersey/onluk/osmanli oyun bot/yeni versiyon/hesapekle.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow2(object):
    def setupUi(self, MainWindow2):
        MainWindow2.setObjectName("MainWindow2")
        MainWindow2.resize(541, 685)
        MainWindow2.setStyleSheet("selection-color: rgb(170, 170, 255);\n"
"background-color: rgb(167, 167, 167);\n"
"alternate-background-color: rgb(85, 0, 0);\n"
"selection-background-color: rgb(85, 255, 127);\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow2)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 571, 661))
        self.scrollArea.setStyleSheet("color: rgb(85, 170, 0);\n"
"selection-color: rgb(170, 170, 255);\n"
"border-top-color: rgb(255, 0, 0);\n"
"background-color: rgb(70, 70, 70);")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 569, 659))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.scrollAreaWidgetContents)
        self.scrollArea_2.setGeometry(QtCore.QRect(0, 0, 531, 541))
        self.scrollArea_2.setStyleSheet("color: rgb(85, 170, 0);\n"
"selection-color: rgb(170, 170, 255);\n"
"border-top-color: rgb(255, 0, 0);\n"
"background-color: rgb(70, 70, 70);")
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 512, 1227))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.email_13 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.email_13.setMinimumSize(QtCore.QSize(240, 41))
        self.email_13.setMaximumSize(QtCore.QSize(240, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.email_13.setFont(font)
        self.email_13.setObjectName("email_13")
        self.gridLayout.addWidget(self.email_13, 28, 2, 1, 1)
        self.email = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.email.setMinimumSize(QtCore.QSize(240, 41))
        self.email.setMaximumSize(QtCore.QSize(240, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.email.setFont(font)
        self.email.setObjectName("email")
        self.gridLayout.addWidget(self.email, 2, 2, 1, 1)
        self.sifre_18 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.sifre_18.setMinimumSize(QtCore.QSize(170, 41))
        self.sifre_18.setMaximumSize(QtCore.QSize(170, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sifre_18.setFont(font)
        self.sifre_18.setObjectName("sifre_18")
        self.gridLayout.addWidget(self.sifre_18, 38, 4, 1, 1)
        self.sira_18 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.sira_18.setMinimumSize(QtCore.QSize(27, 36))
        self.sira_18.setMaximumSize(QtCore.QSize(27, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sira_18.setFont(font)
        self.sira_18.setObjectName("sira_18")
        self.gridLayout.addWidget(self.sira_18, 38, 0, 1, 1)
        self.email_14 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.email_14.setMinimumSize(QtCore.QSize(240, 41))
        self.email_14.setMaximumSize(QtCore.QSize(240, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.email_14.setFont(font)
        self.email_14.setObjectName("email_14")
        self.gridLayout.addWidget(self.email_14, 30, 2, 1, 1)
        self.sira = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.sira.setMinimumSize(QtCore.QSize(25, 36))
        self.sira.setMaximumSize(QtCore.QSize(25, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sira.setFont(font)
        self.sira.setObjectName("sira")
        self.gridLayout.addWidget(self.sira, 2, 0, 1, 1)
        self.email_17 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.email_17.setMinimumSize(QtCore.QSize(240, 41))
        self.email_17.setMaximumSize(QtCore.QSize(240, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.email_17.setFont(font)
        self.email_17.setObjectName("email_17")
        self.gridLayout.addWidget(self.email_17, 36, 2, 1, 1)
        self.email_6 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.email_6.setMinimumSize(QtCore.QSize(240, 41))
        self.email_6.setMaximumSize(QtCore.QSize(240, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.email_6.setFont(font)
        self.email_6.setObjectName("email_6")
        self.gridLayout.addWidget(self.email_6, 13, 2, 1, 1)
        self.sifre_3 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.sifre_3.setMinimumSize(QtCore.QSize(170, 41))
        self.sifre_3.setMaximumSize(QtCore.QSize(170, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sifre_3.setFont(font)
        self.sifre_3.setObjectName("sifre_3")
        self.gridLayout.addWidget(self.sifre_3, 6, 4, 1, 1)
        self.email_9 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.email_9.setMinimumSize(QtCore.QSize(240, 41))
        self.email_9.setMaximumSize(QtCore.QSize(240, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.email_9.setFont(font)
        self.email_9.setObjectName("email_9")
        self.gridLayout.addWidget(self.email_9, 19, 2, 1, 1)
        self.sifre_2 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.sifre_2.setMinimumSize(QtCore.QSize(170, 41))
        self.sifre_2.setMaximumSize(QtCore.QSize(170, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sifre_2.setFont(font)
        self.sifre_2.setObjectName("sifre_2")
        self.gridLayout.addWidget(self.sifre_2, 4, 4, 1, 1)
        self.email_isim = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.email_isim.setMinimumSize(QtCore.QSize(65, 36))
        self.email_isim.setMaximumSize(QtCore.QSize(65, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.email_isim.setFont(font)
        self.email_isim.setObjectName("email_isim")
        self.gridLayout.addWidget(self.email_isim, 0, 2, 1, 1)
        self.sifre_6 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.sifre_6.setMinimumSize(QtCore.QSize(170, 41))
        self.sifre_6.setMaximumSize(QtCore.QSize(170, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sifre_6.setFont(font)
        self.sifre_6.setObjectName("sifre_6")
        self.gridLayout.addWidget(self.sifre_6, 13, 4, 1, 1)
        self.email_15 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.email_15.setMinimumSize(QtCore.QSize(240, 41))
        self.email_15.setMaximumSize(QtCore.QSize(240, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.email_15.setFont(font)
        self.email_15.setObjectName("email_15")
        self.gridLayout.addWidget(self.email_15, 32, 2, 1, 1)
        self.sira_19 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.sira_19.setMinimumSize(QtCore.QSize(27, 36))
        self.sira_19.setMaximumSize(QtCore.QSize(27, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sira_19.setFont(font)
        self.sira_19.setObjectName("sira_19")
        self.gridLayout.addWidget(self.sira_19, 40, 0, 1, 1)
        self.sifre_17 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.sifre_17.setMinimumSize(QtCore.QSize(170, 41))
        self.sifre_17.setMaximumSize(QtCore.QSize(170, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sifre_17.setFont(font)
        self.sifre_17.setObjectName("sifre_17")
        self.gridLayout.addWidget(self.sifre_17, 36, 4, 1, 1)
        self.sira_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.sira_14.setMinimumSize(QtCore.QSize(27, 36))
        self.sira_14.setMaximumSize(QtCore.QSize(27, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sira_14.setFont(font)
        self.sira_14.setObjectName("sira_14")
        self.gridLayout.addWidget(self.sira_14, 30, 0, 1, 1)
        self.email_8 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.email_8.setMinimumSize(QtCore.QSize(240, 41))
        self.email_8.setMaximumSize(QtCore.QSize(240, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.email_8.setFont(font)
        self.email_8.setObjectName("email_8")
        self.gridLayout.addWidget(self.email_8, 17, 2, 1, 1)
        self.email_2 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.email_2.setMinimumSize(QtCore.QSize(240, 41))
        self.email_2.setMaximumSize(QtCore.QSize(240, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.email_2.setFont(font)
        self.email_2.setObjectName("email_2")
        self.gridLayout.addWidget(self.email_2, 4, 2, 1, 1)
        self.sifre_14 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.sifre_14.setMinimumSize(QtCore.QSize(170, 41))
        self.sifre_14.setMaximumSize(QtCore.QSize(170, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sifre_14.setFont(font)
        self.sifre_14.setObjectName("sifre_14")
        self.gridLayout.addWidget(self.sifre_14, 30, 4, 1, 1)
        self.sifre_5 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.sifre_5.setMinimumSize(QtCore.QSize(170, 41))
        self.sifre_5.setMaximumSize(QtCore.QSize(170, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sifre_5.setFont(font)
        self.sifre_5.setObjectName("sifre_5")
        self.gridLayout.addWidget(self.sifre_5, 10, 4, 1, 1)
        self.sifre_10 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.sifre_10.setMinimumSize(QtCore.QSize(170, 41))
        self.sifre_10.setMaximumSize(QtCore.QSize(170, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sifre_10.setFont(font)
        self.sifre_10.setObjectName("sifre_10")
        self.gridLayout.addWidget(self.sifre_10, 21, 4, 1, 1)
        self.sifre_9 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.sifre_9.setMinimumSize(QtCore.QSize(170, 41))
        self.sifre_9.setMaximumSize(QtCore.QSize(170, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sifre_9.setFont(font)
        self.sifre_9.setObjectName("sifre_9")
        self.gridLayout.addWidget(self.sifre_9, 19, 4, 1, 1)
        self.email_12 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.email_12.setMinimumSize(QtCore.QSize(240, 41))
        self.email_12.setMaximumSize(QtCore.QSize(240, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.email_12.setFont(font)
        self.email_12.setObjectName("email_12")
        self.gridLayout.addWidget(self.email_12, 26, 2, 1, 1)
        self.sifre_13 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.sifre_13.setMinimumSize(QtCore.QSize(170, 41))
        self.sifre_13.setMaximumSize(QtCore.QSize(170, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sifre_13.setFont(font)
        self.sifre_13.setObjectName("sifre_13")
        self.gridLayout.addWidget(self.sifre_13, 28, 4, 1, 1)
        self.email_16 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.email_16.setMinimumSize(QtCore.QSize(240, 41))
        self.email_16.setMaximumSize(QtCore.QSize(240, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.email_16.setFont(font)
        self.email_16.setObjectName("email_16")
        self.gridLayout.addWidget(self.email_16, 34, 2, 1, 1)
        self.sifre_7 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.sifre_7.setMinimumSize(QtCore.QSize(170, 41))
        self.sifre_7.setMaximumSize(QtCore.QSize(170, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sifre_7.setFont(font)
        self.sifre_7.setObjectName("sifre_7")
        self.gridLayout.addWidget(self.sifre_7, 15, 4, 1, 1)
        self.sira_20 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.sira_20.setMinimumSize(QtCore.QSize(27, 36))
        self.sira_20.setMaximumSize(QtCore.QSize(27, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sira_20.setFont(font)
        self.sira_20.setObjectName("sira_20")
        self.gridLayout.addWidget(self.sira_20, 42, 0, 1, 1)
        self.sifre_isim = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.sifre_isim.setMinimumSize(QtCore.QSize(65, 36))
        self.sifre_isim.setMaximumSize(QtCore.QSize(65, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sifre_isim.setFont(font)
        self.sifre_isim.setObjectName("sifre_isim")
        self.gridLayout.addWidget(self.sifre_isim, 0, 4, 1, 1)
        self.sira_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.sira_13.setMinimumSize(QtCore.QSize(27, 36))
        self.sira_13.setMaximumSize(QtCore.QSize(27, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sira_13.setFont(font)
        self.sira_13.setObjectName("sira_13")
        self.gridLayout.addWidget(self.sira_13, 28, 0, 1, 1)
        self.email_20 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.email_20.setMinimumSize(QtCore.QSize(240, 41))
        self.email_20.setMaximumSize(QtCore.QSize(240, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.email_20.setFont(font)
        self.email_20.setObjectName("email_20")
        self.gridLayout.addWidget(self.email_20, 42, 2, 1, 1)
        self.email_4 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.email_4.setMinimumSize(QtCore.QSize(240, 41))
        self.email_4.setMaximumSize(QtCore.QSize(240, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.email_4.setFont(font)
        self.email_4.setObjectName("email_4")
        self.gridLayout.addWidget(self.email_4, 8, 2, 1, 1)
        self.email_5 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.email_5.setMinimumSize(QtCore.QSize(240, 41))
        self.email_5.setMaximumSize(QtCore.QSize(240, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.email_5.setFont(font)
        self.email_5.setObjectName("email_5")
        self.gridLayout.addWidget(self.email_5, 10, 2, 1, 1)
        self.email_18 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.email_18.setMinimumSize(QtCore.QSize(240, 41))
        self.email_18.setMaximumSize(QtCore.QSize(240, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.email_18.setFont(font)
        self.email_18.setObjectName("email_18")
        self.gridLayout.addWidget(self.email_18, 38, 2, 1, 1)
        self.email_3 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.email_3.setMinimumSize(QtCore.QSize(240, 41))
        self.email_3.setMaximumSize(QtCore.QSize(240, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.email_3.setFont(font)
        self.email_3.setObjectName("email_3")
        self.gridLayout.addWidget(self.email_3, 6, 2, 1, 1)
        self.line_70 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_70.setMinimumSize(QtCore.QSize(5, 5))
        self.line_70.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_70.setLineWidth(6)
        self.line_70.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_70.setObjectName("line_70")
        self.gridLayout.addWidget(self.line_70, 6, 3, 1, 1)
        self.sira_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.sira_15.setMinimumSize(QtCore.QSize(27, 36))
        self.sira_15.setMaximumSize(QtCore.QSize(27, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sira_15.setFont(font)
        self.sira_15.setObjectName("sira_15")
        self.gridLayout.addWidget(self.sira_15, 32, 0, 1, 1)
        self.sira_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.sira_11.setMinimumSize(QtCore.QSize(27, 36))
        self.sira_11.setMaximumSize(QtCore.QSize(27, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sira_11.setFont(font)
        self.sira_11.setObjectName("sira_11")
        self.gridLayout.addWidget(self.sira_11, 23, 0, 1, 1)
        self.line_84 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_84.setMinimumSize(QtCore.QSize(5, 5))
        self.line_84.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_84.setLineWidth(6)
        self.line_84.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_84.setObjectName("line_84")
        self.gridLayout.addWidget(self.line_84, 30, 1, 1, 1)
        self.line_69 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_69.setMinimumSize(QtCore.QSize(5, 5))
        self.line_69.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_69.setLineWidth(6)
        self.line_69.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_69.setObjectName("line_69")
        self.gridLayout.addWidget(self.line_69, 4, 3, 1, 1)
        self.sifre_20 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.sifre_20.setMinimumSize(QtCore.QSize(170, 41))
        self.sifre_20.setMaximumSize(QtCore.QSize(170, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sifre_20.setFont(font)
        self.sifre_20.setObjectName("sifre_20")
        self.gridLayout.addWidget(self.sifre_20, 42, 4, 1, 1)
        self.sifre_11 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.sifre_11.setMinimumSize(QtCore.QSize(170, 41))
        self.sifre_11.setMaximumSize(QtCore.QSize(170, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sifre_11.setFont(font)
        self.sifre_11.setObjectName("sifre_11")
        self.gridLayout.addWidget(self.sifre_11, 23, 4, 1, 1)
        self.line_58 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_58.setMinimumSize(QtCore.QSize(5, 5))
        self.line_58.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_58.setLineWidth(6)
        self.line_58.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_58.setObjectName("line_58")
        self.gridLayout.addWidget(self.line_58, 0, 1, 1, 1)
        self.line_99 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_99.setMinimumSize(QtCore.QSize(5, 5))
        self.line_99.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_99.setLineWidth(6)
        self.line_99.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_99.setObjectName("line_99")
        self.gridLayout.addWidget(self.line_99, 36, 1, 1, 1)
        self.line_63 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_63.setMinimumSize(QtCore.QSize(5, 5))
        self.line_63.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_63.setLineWidth(6)
        self.line_63.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_63.setObjectName("line_63")
        self.gridLayout.addWidget(self.line_63, 10, 1, 1, 1)
        self.line_94 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_94.setMinimumSize(QtCore.QSize(5, 5))
        self.line_94.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_94.setLineWidth(6)
        self.line_94.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_94.setObjectName("line_94")
        self.gridLayout.addWidget(self.line_94, 40, 3, 1, 1)
        self.line_61 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_61.setMinimumSize(QtCore.QSize(5, 5))
        self.line_61.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_61.setLineWidth(6)
        self.line_61.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_61.setObjectName("line_61")
        self.gridLayout.addWidget(self.line_61, 6, 1, 1, 1)
        self.line_80 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_80.setMinimumSize(QtCore.QSize(5, 5))
        self.line_80.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_80.setLineWidth(6)
        self.line_80.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_80.setObjectName("line_80")
        self.gridLayout.addWidget(self.line_80, 28, 3, 1, 1)
        self.line_59 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_59.setMinimumSize(QtCore.QSize(5, 5))
        self.line_59.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_59.setLineWidth(6)
        self.line_59.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_59.setObjectName("line_59")
        self.gridLayout.addWidget(self.line_59, 2, 1, 1, 1)
        self.line_62 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_62.setMinimumSize(QtCore.QSize(5, 5))
        self.line_62.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_62.setLineWidth(6)
        self.line_62.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_62.setObjectName("line_62")
        self.gridLayout.addWidget(self.line_62, 8, 1, 1, 1)
        self.line_65 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_65.setMinimumSize(QtCore.QSize(5, 5))
        self.line_65.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_65.setLineWidth(6)
        self.line_65.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_65.setObjectName("line_65")
        self.gridLayout.addWidget(self.line_65, 15, 1, 1, 1)
        self.line_67 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_67.setMinimumSize(QtCore.QSize(5, 5))
        self.line_67.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_67.setLineWidth(6)
        self.line_67.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_67.setObjectName("line_67")
        self.gridLayout.addWidget(self.line_67, 0, 3, 1, 1)
        self.line_81 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_81.setMinimumSize(QtCore.QSize(5, 5))
        self.line_81.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_81.setLineWidth(6)
        self.line_81.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_81.setObjectName("line_81")
        self.gridLayout.addWidget(self.line_81, 30, 3, 1, 1)
        self.line_91 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_91.setMinimumSize(QtCore.QSize(5, 5))
        self.line_91.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_91.setLineWidth(6)
        self.line_91.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_91.setObjectName("line_91")
        self.gridLayout.addWidget(self.line_91, 34, 1, 1, 1)
        self.line_76 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_76.setMinimumSize(QtCore.QSize(5, 5))
        self.line_76.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_76.setLineWidth(6)
        self.line_76.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_76.setObjectName("line_76")
        self.gridLayout.addWidget(self.line_76, 19, 3, 1, 1)
        self.line_64 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_64.setMinimumSize(QtCore.QSize(5, 5))
        self.line_64.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_64.setLineWidth(6)
        self.line_64.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_64.setObjectName("line_64")
        self.gridLayout.addWidget(self.line_64, 13, 1, 1, 1)
        self.line_95 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_95.setMinimumSize(QtCore.QSize(5, 5))
        self.line_95.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_95.setLineWidth(6)
        self.line_95.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_95.setObjectName("line_95")
        self.gridLayout.addWidget(self.line_95, 42, 3, 1, 1)
        self.line_89 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_89.setMinimumSize(QtCore.QSize(5, 5))
        self.line_89.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_89.setLineWidth(6)
        self.line_89.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_89.setObjectName("line_89")
        self.gridLayout.addWidget(self.line_89, 21, 1, 1, 1)
        self.line_72 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_72.setMinimumSize(QtCore.QSize(5, 5))
        self.line_72.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_72.setLineWidth(6)
        self.line_72.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_72.setObjectName("line_72")
        self.gridLayout.addWidget(self.line_72, 10, 3, 1, 1)
        self.line_74 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_74.setMinimumSize(QtCore.QSize(5, 5))
        self.line_74.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_74.setLineWidth(6)
        self.line_74.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_74.setObjectName("line_74")
        self.gridLayout.addWidget(self.line_74, 15, 3, 1, 1)
        self.line_90 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_90.setMinimumSize(QtCore.QSize(5, 5))
        self.line_90.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_90.setLineWidth(6)
        self.line_90.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_90.setObjectName("line_90")
        self.gridLayout.addWidget(self.line_90, 32, 1, 1, 1)
        self.line_86 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_86.setMinimumSize(QtCore.QSize(5, 5))
        self.line_86.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_86.setLineWidth(6)
        self.line_86.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_86.setObjectName("line_86")
        self.gridLayout.addWidget(self.line_86, 26, 1, 1, 1)
        self.line_77 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_77.setMinimumSize(QtCore.QSize(5, 5))
        self.line_77.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_77.setLineWidth(6)
        self.line_77.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_77.setObjectName("line_77")
        self.gridLayout.addWidget(self.line_77, 21, 3, 1, 1)
        self.line_83 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_83.setMinimumSize(QtCore.QSize(5, 5))
        self.line_83.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_83.setLineWidth(6)
        self.line_83.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_83.setObjectName("line_83")
        self.gridLayout.addWidget(self.line_83, 34, 3, 1, 1)
        self.line_71 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_71.setMinimumSize(QtCore.QSize(5, 5))
        self.line_71.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_71.setLineWidth(6)
        self.line_71.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_71.setObjectName("line_71")
        self.gridLayout.addWidget(self.line_71, 8, 3, 1, 1)
        self.line_85 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_85.setMinimumSize(QtCore.QSize(5, 5))
        self.line_85.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_85.setLineWidth(6)
        self.line_85.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_85.setObjectName("line_85")
        self.gridLayout.addWidget(self.line_85, 28, 1, 1, 1)
        self.line_78 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_78.setMinimumSize(QtCore.QSize(5, 5))
        self.line_78.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_78.setLineWidth(6)
        self.line_78.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_78.setObjectName("line_78")
        self.gridLayout.addWidget(self.line_78, 23, 3, 1, 1)
        self.line_96 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_96.setMinimumSize(QtCore.QSize(5, 5))
        self.line_96.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_96.setLineWidth(6)
        self.line_96.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_96.setObjectName("line_96")
        self.gridLayout.addWidget(self.line_96, 42, 1, 1, 1)
        self.line_88 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_88.setMinimumSize(QtCore.QSize(5, 5))
        self.line_88.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_88.setLineWidth(6)
        self.line_88.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_88.setObjectName("line_88")
        self.gridLayout.addWidget(self.line_88, 19, 1, 1, 1)
        self.line_87 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_87.setMinimumSize(QtCore.QSize(5, 5))
        self.line_87.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_87.setLineWidth(6)
        self.line_87.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_87.setObjectName("line_87")
        self.gridLayout.addWidget(self.line_87, 23, 1, 1, 1)
        self.line_92 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_92.setMinimumSize(QtCore.QSize(5, 5))
        self.line_92.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_92.setLineWidth(6)
        self.line_92.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_92.setObjectName("line_92")
        self.gridLayout.addWidget(self.line_92, 36, 3, 1, 1)
        self.line_98 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_98.setMinimumSize(QtCore.QSize(5, 5))
        self.line_98.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_98.setLineWidth(6)
        self.line_98.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_98.setObjectName("line_98")
        self.gridLayout.addWidget(self.line_98, 38, 1, 1, 1)
        self.line_66 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_66.setMinimumSize(QtCore.QSize(5, 5))
        self.line_66.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_66.setLineWidth(6)
        self.line_66.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_66.setObjectName("line_66")
        self.gridLayout.addWidget(self.line_66, 17, 1, 1, 1)
        self.line_68 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_68.setMinimumSize(QtCore.QSize(5, 5))
        self.line_68.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_68.setLineWidth(6)
        self.line_68.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_68.setObjectName("line_68")
        self.gridLayout.addWidget(self.line_68, 2, 3, 1, 1)
        self.line_75 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_75.setMinimumSize(QtCore.QSize(5, 5))
        self.line_75.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_75.setLineWidth(6)
        self.line_75.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_75.setObjectName("line_75")
        self.gridLayout.addWidget(self.line_75, 17, 3, 1, 1)
        self.line_73 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_73.setMinimumSize(QtCore.QSize(5, 5))
        self.line_73.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_73.setLineWidth(6)
        self.line_73.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_73.setObjectName("line_73")
        self.gridLayout.addWidget(self.line_73, 13, 3, 1, 1)
        self.line_93 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_93.setMinimumSize(QtCore.QSize(5, 5))
        self.line_93.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_93.setLineWidth(6)
        self.line_93.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_93.setObjectName("line_93")
        self.gridLayout.addWidget(self.line_93, 38, 3, 1, 1)
        self.line_97 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_97.setMinimumSize(QtCore.QSize(5, 5))
        self.line_97.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_97.setLineWidth(6)
        self.line_97.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_97.setObjectName("line_97")
        self.gridLayout.addWidget(self.line_97, 40, 1, 1, 1)
        self.line_79 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_79.setMinimumSize(QtCore.QSize(5, 5))
        self.line_79.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_79.setLineWidth(6)
        self.line_79.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_79.setObjectName("line_79")
        self.gridLayout.addWidget(self.line_79, 26, 3, 1, 1)
        self.line_82 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_82.setMinimumSize(QtCore.QSize(5, 5))
        self.line_82.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_82.setLineWidth(6)
        self.line_82.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_82.setObjectName("line_82")
        self.gridLayout.addWidget(self.line_82, 32, 3, 1, 1)
        self.line_60 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_60.setMinimumSize(QtCore.QSize(5, 5))
        self.line_60.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_60.setLineWidth(6)
        self.line_60.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_60.setObjectName("line_60")
        self.gridLayout.addWidget(self.line_60, 4, 1, 1, 1)
        self.sifre_8 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.sifre_8.setMinimumSize(QtCore.QSize(170, 41))
        self.sifre_8.setMaximumSize(QtCore.QSize(170, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sifre_8.setFont(font)
        self.sifre_8.setObjectName("sifre_8")
        self.gridLayout.addWidget(self.sifre_8, 17, 4, 1, 1)
        self.sifre_12 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.sifre_12.setMinimumSize(QtCore.QSize(170, 41))
        self.sifre_12.setMaximumSize(QtCore.QSize(170, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sifre_12.setFont(font)
        self.sifre_12.setObjectName("sifre_12")
        self.gridLayout.addWidget(self.sifre_12, 26, 4, 1, 1)
        self.sira_16 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.sira_16.setMinimumSize(QtCore.QSize(27, 36))
        self.sira_16.setMaximumSize(QtCore.QSize(27, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sira_16.setFont(font)
        self.sira_16.setObjectName("sira_16")
        self.gridLayout.addWidget(self.sira_16, 34, 0, 1, 1)
        self.sifre_16 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.sifre_16.setMinimumSize(QtCore.QSize(170, 41))
        self.sifre_16.setMaximumSize(QtCore.QSize(170, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sifre_16.setFont(font)
        self.sifre_16.setObjectName("sifre_16")
        self.gridLayout.addWidget(self.sifre_16, 34, 4, 1, 1)
        self.sira_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.sira_12.setMinimumSize(QtCore.QSize(27, 36))
        self.sira_12.setMaximumSize(QtCore.QSize(27, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sira_12.setFont(font)
        self.sira_12.setObjectName("sira_12")
        self.gridLayout.addWidget(self.sira_12, 26, 0, 1, 1)
        self.email_19 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.email_19.setMinimumSize(QtCore.QSize(240, 41))
        self.email_19.setMaximumSize(QtCore.QSize(240, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.email_19.setFont(font)
        self.email_19.setObjectName("email_19")
        self.gridLayout.addWidget(self.email_19, 40, 2, 1, 1)
        self.sira_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.sira_10.setMinimumSize(QtCore.QSize(27, 36))
        self.sira_10.setMaximumSize(QtCore.QSize(27, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sira_10.setFont(font)
        self.sira_10.setObjectName("sira_10")
        self.gridLayout.addWidget(self.sira_10, 21, 0, 1, 1)
        self.sira_17 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.sira_17.setMinimumSize(QtCore.QSize(27, 36))
        self.sira_17.setMaximumSize(QtCore.QSize(27, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sira_17.setFont(font)
        self.sira_17.setObjectName("sira_17")
        self.gridLayout.addWidget(self.sira_17, 36, 0, 1, 1)
        self.sifre = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.sifre.setMinimumSize(QtCore.QSize(170, 41))
        self.sifre.setMaximumSize(QtCore.QSize(170, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sifre.setFont(font)
        self.sifre.setObjectName("sifre")
        self.gridLayout.addWidget(self.sifre, 2, 4, 1, 1)
        self.email_10 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.email_10.setMinimumSize(QtCore.QSize(240, 41))
        self.email_10.setMaximumSize(QtCore.QSize(240, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.email_10.setFont(font)
        self.email_10.setObjectName("email_10")
        self.gridLayout.addWidget(self.email_10, 21, 2, 1, 1)
        self.sifre_4 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.sifre_4.setMinimumSize(QtCore.QSize(170, 41))
        self.sifre_4.setMaximumSize(QtCore.QSize(170, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sifre_4.setFont(font)
        self.sifre_4.setObjectName("sifre_4")
        self.gridLayout.addWidget(self.sifre_4, 8, 4, 1, 1)
        self.sifre_19 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.sifre_19.setMinimumSize(QtCore.QSize(170, 41))
        self.sifre_19.setMaximumSize(QtCore.QSize(170, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sifre_19.setFont(font)
        self.sifre_19.setObjectName("sifre_19")
        self.gridLayout.addWidget(self.sifre_19, 40, 4, 1, 1)
        self.sifre_15 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.sifre_15.setMinimumSize(QtCore.QSize(170, 41))
        self.sifre_15.setMaximumSize(QtCore.QSize(170, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sifre_15.setFont(font)
        self.sifre_15.setObjectName("sifre_15")
        self.gridLayout.addWidget(self.sifre_15, 32, 4, 1, 1)
        self.email_7 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.email_7.setMinimumSize(QtCore.QSize(240, 41))
        self.email_7.setMaximumSize(QtCore.QSize(240, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.email_7.setFont(font)
        self.email_7.setObjectName("email_7")
        self.gridLayout.addWidget(self.email_7, 15, 2, 1, 1)
        self.email_11 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.email_11.setMinimumSize(QtCore.QSize(240, 41))
        self.email_11.setMaximumSize(QtCore.QSize(240, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.email_11.setFont(font)
        self.email_11.setObjectName("email_11")
        self.gridLayout.addWidget(self.email_11, 23, 2, 1, 1)
        self.sira_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.sira_8.setMinimumSize(QtCore.QSize(25, 36))
        self.sira_8.setMaximumSize(QtCore.QSize(25, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sira_8.setFont(font)
        self.sira_8.setObjectName("sira_8")
        self.gridLayout.addWidget(self.sira_8, 17, 0, 1, 1)
        self.sira_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.sira_9.setMinimumSize(QtCore.QSize(25, 36))
        self.sira_9.setMaximumSize(QtCore.QSize(25, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sira_9.setFont(font)
        self.sira_9.setObjectName("sira_9")
        self.gridLayout.addWidget(self.sira_9, 19, 0, 1, 1)
        self.sira_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.sira_4.setMinimumSize(QtCore.QSize(25, 36))
        self.sira_4.setMaximumSize(QtCore.QSize(25, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sira_4.setFont(font)
        self.sira_4.setObjectName("sira_4")
        self.gridLayout.addWidget(self.sira_4, 8, 0, 1, 1)
        self.sira_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.sira_5.setMinimumSize(QtCore.QSize(25, 36))
        self.sira_5.setMaximumSize(QtCore.QSize(25, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sira_5.setFont(font)
        self.sira_5.setObjectName("sira_5")
        self.gridLayout.addWidget(self.sira_5, 10, 0, 1, 1)
        self.sira_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.sira_7.setMinimumSize(QtCore.QSize(25, 36))
        self.sira_7.setMaximumSize(QtCore.QSize(25, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sira_7.setFont(font)
        self.sira_7.setObjectName("sira_7")
        self.gridLayout.addWidget(self.sira_7, 15, 0, 1, 1)
        self.sira_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.sira_3.setMinimumSize(QtCore.QSize(25, 36))
        self.sira_3.setMaximumSize(QtCore.QSize(25, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sira_3.setFont(font)
        self.sira_3.setObjectName("sira_3")
        self.gridLayout.addWidget(self.sira_3, 6, 0, 1, 1)
        self.sira_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.sira_2.setMinimumSize(QtCore.QSize(25, 36))
        self.sira_2.setMaximumSize(QtCore.QSize(25, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sira_2.setFont(font)
        self.sira_2.setObjectName("sira_2")
        self.gridLayout.addWidget(self.sira_2, 4, 0, 1, 1)
        self.sira_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.sira_6.setMinimumSize(QtCore.QSize(25, 36))
        self.sira_6.setMaximumSize(QtCore.QSize(25, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sira_6.setFont(font)
        self.sira_6.setObjectName("sira_6")
        self.gridLayout.addWidget(self.sira_6, 13, 0, 1, 1)
        self.line_21 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_21.setMinimumSize(QtCore.QSize(5, 5))
        self.line_21.setSizeIncrement(QtCore.QSize(50, 50))
        self.line_21.setBaseSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.line_21.setFont(font)
        self.line_21.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.line_21.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_21.setLineWidth(6)
        self.line_21.setMidLineWidth(0)
        self.line_21.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_21.setObjectName("line_21")
        self.gridLayout.addWidget(self.line_21, 43, 0, 1, 5)
        self.line_20 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_20.setMinimumSize(QtCore.QSize(5, 5))
        self.line_20.setSizeIncrement(QtCore.QSize(50, 50))
        self.line_20.setBaseSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.line_20.setFont(font)
        self.line_20.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.line_20.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_20.setLineWidth(6)
        self.line_20.setMidLineWidth(0)
        self.line_20.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_20.setObjectName("line_20")
        self.gridLayout.addWidget(self.line_20, 41, 0, 1, 5)
        self.line_19 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_19.setMinimumSize(QtCore.QSize(5, 5))
        self.line_19.setSizeIncrement(QtCore.QSize(50, 50))
        self.line_19.setBaseSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.line_19.setFont(font)
        self.line_19.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.line_19.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_19.setLineWidth(6)
        self.line_19.setMidLineWidth(0)
        self.line_19.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_19.setObjectName("line_19")
        self.gridLayout.addWidget(self.line_19, 39, 0, 1, 5)
        self.line_18 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_18.setMinimumSize(QtCore.QSize(5, 5))
        self.line_18.setSizeIncrement(QtCore.QSize(50, 50))
        self.line_18.setBaseSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.line_18.setFont(font)
        self.line_18.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.line_18.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_18.setLineWidth(6)
        self.line_18.setMidLineWidth(0)
        self.line_18.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_18.setObjectName("line_18")
        self.gridLayout.addWidget(self.line_18, 37, 0, 1, 5)
        self.line_17 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_17.setMinimumSize(QtCore.QSize(5, 5))
        self.line_17.setSizeIncrement(QtCore.QSize(50, 50))
        self.line_17.setBaseSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.line_17.setFont(font)
        self.line_17.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.line_17.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_17.setLineWidth(6)
        self.line_17.setMidLineWidth(0)
        self.line_17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_17.setObjectName("line_17")
        self.gridLayout.addWidget(self.line_17, 35, 0, 1, 5)
        self.line_16 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_16.setMinimumSize(QtCore.QSize(5, 5))
        self.line_16.setSizeIncrement(QtCore.QSize(50, 50))
        self.line_16.setBaseSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.line_16.setFont(font)
        self.line_16.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.line_16.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_16.setLineWidth(6)
        self.line_16.setMidLineWidth(0)
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setObjectName("line_16")
        self.gridLayout.addWidget(self.line_16, 33, 0, 1, 5)
        self.line_15 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_15.setMinimumSize(QtCore.QSize(5, 5))
        self.line_15.setSizeIncrement(QtCore.QSize(50, 50))
        self.line_15.setBaseSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.line_15.setFont(font)
        self.line_15.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.line_15.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_15.setLineWidth(6)
        self.line_15.setMidLineWidth(0)
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setObjectName("line_15")
        self.gridLayout.addWidget(self.line_15, 31, 0, 1, 5)
        self.line_14 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_14.setMinimumSize(QtCore.QSize(5, 5))
        self.line_14.setSizeIncrement(QtCore.QSize(50, 50))
        self.line_14.setBaseSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.line_14.setFont(font)
        self.line_14.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.line_14.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_14.setLineWidth(6)
        self.line_14.setMidLineWidth(0)
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setObjectName("line_14")
        self.gridLayout.addWidget(self.line_14, 29, 0, 1, 5)
        self.line_13 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_13.setMinimumSize(QtCore.QSize(5, 5))
        self.line_13.setSizeIncrement(QtCore.QSize(50, 50))
        self.line_13.setBaseSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.line_13.setFont(font)
        self.line_13.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.line_13.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_13.setLineWidth(6)
        self.line_13.setMidLineWidth(0)
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setObjectName("line_13")
        self.gridLayout.addWidget(self.line_13, 27, 0, 1, 5)
        self.line_12 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_12.setMinimumSize(QtCore.QSize(5, 5))
        self.line_12.setSizeIncrement(QtCore.QSize(50, 50))
        self.line_12.setBaseSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.line_12.setFont(font)
        self.line_12.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.line_12.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_12.setLineWidth(6)
        self.line_12.setMidLineWidth(0)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setObjectName("line_12")
        self.gridLayout.addWidget(self.line_12, 24, 0, 1, 5)
        self.line_11 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_11.setMinimumSize(QtCore.QSize(5, 5))
        self.line_11.setSizeIncrement(QtCore.QSize(50, 50))
        self.line_11.setBaseSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.line_11.setFont(font)
        self.line_11.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.line_11.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_11.setLineWidth(6)
        self.line_11.setMidLineWidth(0)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setObjectName("line_11")
        self.gridLayout.addWidget(self.line_11, 22, 0, 1, 5)
        self.line_10 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_10.setMinimumSize(QtCore.QSize(5, 5))
        self.line_10.setSizeIncrement(QtCore.QSize(50, 50))
        self.line_10.setBaseSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.line_10.setFont(font)
        self.line_10.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.line_10.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_10.setLineWidth(6)
        self.line_10.setMidLineWidth(0)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setObjectName("line_10")
        self.gridLayout.addWidget(self.line_10, 20, 0, 1, 5)
        self.line_9 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_9.setMinimumSize(QtCore.QSize(5, 5))
        self.line_9.setSizeIncrement(QtCore.QSize(50, 50))
        self.line_9.setBaseSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.line_9.setFont(font)
        self.line_9.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.line_9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_9.setLineWidth(6)
        self.line_9.setMidLineWidth(0)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setObjectName("line_9")
        self.gridLayout.addWidget(self.line_9, 18, 0, 1, 5)
        self.line_8 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_8.setMinimumSize(QtCore.QSize(5, 5))
        self.line_8.setSizeIncrement(QtCore.QSize(50, 50))
        self.line_8.setBaseSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.line_8.setFont(font)
        self.line_8.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.line_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_8.setLineWidth(6)
        self.line_8.setMidLineWidth(0)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setObjectName("line_8")
        self.gridLayout.addWidget(self.line_8, 16, 0, 1, 5)
        self.line_7 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_7.setMinimumSize(QtCore.QSize(5, 5))
        self.line_7.setSizeIncrement(QtCore.QSize(50, 50))
        self.line_7.setBaseSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.line_7.setFont(font)
        self.line_7.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.line_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_7.setLineWidth(6)
        self.line_7.setMidLineWidth(0)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setObjectName("line_7")
        self.gridLayout.addWidget(self.line_7, 14, 0, 1, 5)
        self.line_6 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_6.setMinimumSize(QtCore.QSize(5, 5))
        self.line_6.setSizeIncrement(QtCore.QSize(50, 50))
        self.line_6.setBaseSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.line_6.setFont(font)
        self.line_6.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.line_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_6.setLineWidth(6)
        self.line_6.setMidLineWidth(0)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setObjectName("line_6")
        self.gridLayout.addWidget(self.line_6, 12, 0, 1, 5)
        self.line_5 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_5.setMinimumSize(QtCore.QSize(5, 5))
        self.line_5.setSizeIncrement(QtCore.QSize(50, 50))
        self.line_5.setBaseSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.line_5.setFont(font)
        self.line_5.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.line_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_5.setLineWidth(6)
        self.line_5.setMidLineWidth(0)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setObjectName("line_5")
        self.gridLayout.addWidget(self.line_5, 9, 0, 1, 5)
        self.line_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_4.setMinimumSize(QtCore.QSize(5, 5))
        self.line_4.setSizeIncrement(QtCore.QSize(50, 50))
        self.line_4.setBaseSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.line_4.setFont(font)
        self.line_4.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.line_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_4.setLineWidth(6)
        self.line_4.setMidLineWidth(0)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 7, 0, 1, 5)
        self.line_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_3.setMinimumSize(QtCore.QSize(5, 5))
        self.line_3.setSizeIncrement(QtCore.QSize(50, 50))
        self.line_3.setBaseSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.line_3.setFont(font)
        self.line_3.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.line_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_3.setLineWidth(6)
        self.line_3.setMidLineWidth(0)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 5, 0, 1, 5)
        self.line_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_2.setMinimumSize(QtCore.QSize(5, 5))
        self.line_2.setSizeIncrement(QtCore.QSize(50, 50))
        self.line_2.setBaseSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.line_2.setFont(font)
        self.line_2.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setLineWidth(6)
        self.line_2.setMidLineWidth(0)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 3, 0, 1, 5)
        self.line_22 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_22.setMinimumSize(QtCore.QSize(5, 5))
        self.line_22.setSizeIncrement(QtCore.QSize(50, 50))
        self.line_22.setBaseSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.line_22.setFont(font)
        self.line_22.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.line_22.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_22.setLineWidth(6)
        self.line_22.setMidLineWidth(0)
        self.line_22.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_22.setObjectName("line_22")
        self.gridLayout.addWidget(self.line_22, 1, 0, 1, 5)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.save = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.save.setGeometry(QtCore.QRect(430, 590, 111, 51))
        self.save.setObjectName("save")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow2.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(MainWindow2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.toolBar.setFont(font)
        self.toolBar.setMouseTracking(False)
        self.toolBar.setObjectName("toolBar")
        MainWindow2.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionGiri = QtWidgets.QAction(MainWindow2)
        self.actionGiri.setObjectName("actionGiri")
        self.actionHesaplar_Ekle = QtWidgets.QAction(MainWindow2)
        self.actionHesaplar_Ekle.setObjectName("actionHesaplar_Ekle")
        self.actionBot_Ba_lar = QtWidgets.QAction(MainWindow2)
        self.actionBot_Ba_lar.setObjectName("actionBot_Ba_lar")
        self.actionGiri_2 = QtWidgets.QAction(MainWindow2)
        self.actionGiri_2.setObjectName("actionGiri_2")
        self.actionHesap_Ekle = QtWidgets.QAction(MainWindow2)
        self.actionHesap_Ekle.setObjectName("actionHesap_Ekle")
        self.actionBot_Ba_lat = QtWidgets.QAction(MainWindow2)
        self.actionBot_Ba_lat.setObjectName("actionBot_Ba_lat")
        self.toolBar.addAction(self.actionGiri_2)
        self.toolBar.addAction(self.actionHesap_Ekle)
        self.toolBar.addAction(self.actionBot_Ba_lat)

        self.retranslateUi(MainWindow2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow2)

    def retranslateUi(self, MainWindow2):
        _translate = QtCore.QCoreApplication.translate
        MainWindow2.setWindowTitle(_translate("MainWindow2", "MainWindow"))
        self.sira_18.setText(_translate("MainWindow2", "18"))
        self.sira.setText(_translate("MainWindow2", "1"))
        self.email_isim.setText(_translate("MainWindow2", "E-mail"))
        self.sira_19.setText(_translate("MainWindow2", "19"))
        self.sira_14.setText(_translate("MainWindow2", "14"))
        self.sira_20.setText(_translate("MainWindow2", "20"))
        self.sifre_isim.setText(_translate("MainWindow2", "Pass"))
        self.sira_13.setText(_translate("MainWindow2", "13"))
        self.sira_15.setText(_translate("MainWindow2", "15"))
        self.sira_11.setText(_translate("MainWindow2", "11"))
        self.sira_16.setText(_translate("MainWindow2", "16"))
        self.sira_12.setText(_translate("MainWindow2", "12"))
        self.sira_10.setText(_translate("MainWindow2", "10"))
        self.sira_17.setText(_translate("MainWindow2", "17"))
        self.sira_8.setText(_translate("MainWindow2", "8"))
        self.sira_9.setText(_translate("MainWindow2", "9"))
        self.sira_4.setText(_translate("MainWindow2", "4"))
        self.sira_5.setText(_translate("MainWindow2", "5"))
        self.sira_7.setText(_translate("MainWindow2", "7"))
        self.sira_3.setText(_translate("MainWindow2", "3"))
        self.sira_2.setText(_translate("MainWindow2", "2"))
        self.sira_6.setText(_translate("MainWindow2", "6"))
        self.save.setText(_translate("MainWindow2", "Save"))
        self.toolBar.setWindowTitle(_translate("MainWindow2", "toolBar"))
        self.actionGiri.setText(_translate("MainWindow2", "Giriş"))
        self.actionHesaplar_Ekle.setText(_translate("MainWindow2", "Hesapları Ekle"))
        self.actionBot_Ba_lar.setText(_translate("MainWindow2", "Bot Başlat"))
        self.actionGiri_2.setText(_translate("MainWindow2", "Giriş"))
        self.actionHesap_Ekle.setText(_translate("MainWindow2", "Hesap Ekle"))
        self.actionBot_Ba_lat.setText(_translate("MainWindow2", "Bot Başlat"))

