# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/masaüstü/yazılımileilgilihersey/onluk/osmanli oyun bot/yeni versiyon/BOT-GUI/BOT/BOT-GUI/hesapekle.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow2(object):
    def setupUi(self, MainWindow2):
        MainWindow2.setObjectName("MainWindow2")
        MainWindow2.resize(541, 685)
        MainWindow2.setStyleSheet("selection-color: rgb(0, 0, 0);\n"
"background-color: rgb(245, 245, 245);\n"
"alternate-background-color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(0, 0, 100);\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow2)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 571, 661))
        self.scrollArea.setStyleSheet("color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"selection-color: rgb(170, 170, 255);\n"
"border-top-color: rgb(255, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 569, 659))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.scrollAreaWidgetContents)
        self.scrollArea_2.setGeometry(QtCore.QRect(-10, 0, 531, 571))
        self.scrollArea_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"selection-color: rgb(255, 255, 255);\n"
"border-top-color: rgb(255, 255, 255);n"
"background-color:  rgb(255,255,255);")
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, -78, 512, 647))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.email_6 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.email_6.setMinimumSize(QtCore.QSize(240, 41))
        self.email_6.setMaximumSize(QtCore.QSize(240, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.email_6.setFont(font)
        self.email_6.setObjectName("email_6")
        self.gridLayout.addWidget(self.email_6, 13, 2, 1, 1)
        self.sira = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.sira.setMinimumSize(QtCore.QSize(25, 36))
        self.sira.setMaximumSize(QtCore.QSize(25, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sira.setFont(font)
        self.sira.setObjectName("sira")
        self.gridLayout.addWidget(self.sira, 2, 0, 1, 1)
        self.email = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.email.setMinimumSize(QtCore.QSize(240, 41))
        self.email.setMaximumSize(QtCore.QSize(240, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.email.setFont(font)
        self.email.setObjectName("email")
        self.gridLayout.addWidget(self.email, 2, 2, 1, 1)
        self.email_2 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.email_2.setMinimumSize(QtCore.QSize(240, 41))
        self.email_2.setMaximumSize(QtCore.QSize(240, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.email_2.setFont(font)
        self.email_2.setObjectName("email_2")
        self.gridLayout.addWidget(self.email_2, 4, 2, 1, 1)
        self.email_isim = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.email_isim.setMinimumSize(QtCore.QSize(65, 36))
        self.email_isim.setMaximumSize(QtCore.QSize(65, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.email_isim.setFont(font)
        self.email_isim.setObjectName("email_isim")
        self.gridLayout.addWidget(self.email_isim, 0, 2, 1, 1)
        self.sifre_2 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.sifre_2.setMinimumSize(QtCore.QSize(170, 41))
        self.sifre_2.setMaximumSize(QtCore.QSize(170, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sifre_2.setFont(font)
        self.sifre_2.setObjectName("sifre_2")
        self.gridLayout.addWidget(self.sifre_2, 4, 4, 1, 1)
        self.email_9 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.email_9.setMinimumSize(QtCore.QSize(240, 41))
        self.email_9.setMaximumSize(QtCore.QSize(240, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.email_9.setFont(font)
        self.email_9.setObjectName("email_9")
        self.gridLayout.addWidget(self.email_9, 19, 2, 1, 1)
        self.sifre_6 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.sifre_6.setMinimumSize(QtCore.QSize(170, 41))
        self.sifre_6.setMaximumSize(QtCore.QSize(170, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sifre_6.setFont(font)
        self.sifre_6.setObjectName("sifre_6")
        self.gridLayout.addWidget(self.sifre_6, 13, 4, 1, 1)
        self.email_8 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.email_8.setMinimumSize(QtCore.QSize(240, 41))
        self.email_8.setMaximumSize(QtCore.QSize(240, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.email_8.setFont(font)
        self.email_8.setObjectName("email_8")
        self.gridLayout.addWidget(self.email_8, 17, 2, 1, 1)
        self.sifre_3 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.sifre_3.setMinimumSize(QtCore.QSize(170, 41))
        self.sifre_3.setMaximumSize(QtCore.QSize(170, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sifre_3.setFont(font)
        self.sifre_3.setObjectName("sifre_3")
        self.gridLayout.addWidget(self.sifre_3, 6, 4, 1, 1)
        self.sifre_isim = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.sifre_isim.setMinimumSize(QtCore.QSize(65, 36))
        self.sifre_isim.setMaximumSize(QtCore.QSize(65, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sifre_isim.setFont(font)
        self.sifre_isim.setObjectName("sifre_isim")
        self.gridLayout.addWidget(self.sifre_isim, 0, 4, 1, 1)
        self.sifre_9 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.sifre_9.setMinimumSize(QtCore.QSize(170, 41))
        self.sifre_9.setMaximumSize(QtCore.QSize(170, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sifre_9.setFont(font)
        self.sifre_9.setObjectName("sifre_9")
        self.gridLayout.addWidget(self.sifre_9, 19, 4, 1, 1)
        self.sifre_5 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.sifre_5.setMinimumSize(QtCore.QSize(170, 41))
        self.sifre_5.setMaximumSize(QtCore.QSize(170, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sifre_5.setFont(font)
        self.sifre_5.setObjectName("sifre_5")
        self.gridLayout.addWidget(self.sifre_5, 10, 4, 1, 1)
        self.sifre_10 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.sifre_10.setMinimumSize(QtCore.QSize(170, 41))
        self.sifre_10.setMaximumSize(QtCore.QSize(170, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sifre_10.setFont(font)
        self.sifre_10.setObjectName("sifre_10")
        self.gridLayout.addWidget(self.sifre_10, 21, 4, 1, 1)
        self.sifre_7 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.sifre_7.setMinimumSize(QtCore.QSize(170, 41))
        self.sifre_7.setMaximumSize(QtCore.QSize(170, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sifre_7.setFont(font)
        self.sifre_7.setObjectName("sifre_7")
        self.gridLayout.addWidget(self.sifre_7, 15, 4, 1, 1)
        self.line_61 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_61.setMinimumSize(QtCore.QSize(5, 5))
        self.line_61.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_61.setLineWidth(6)
        self.line_61.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_61.setObjectName("line_61")
        self.gridLayout.addWidget(self.line_61, 6, 1, 1, 1)
        self.line_70 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_70.setMinimumSize(QtCore.QSize(5, 5))
        self.line_70.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_70.setLineWidth(6)
        self.line_70.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_70.setObjectName("line_70")
        self.gridLayout.addWidget(self.line_70, 6, 3, 1, 1)
        self.line_59 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_59.setMinimumSize(QtCore.QSize(5, 5))
        self.line_59.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_59.setLineWidth(6)
        self.line_59.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_59.setObjectName("line_59")
        self.gridLayout.addWidget(self.line_59, 2, 1, 1, 1)
        self.email_3 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.email_3.setMinimumSize(QtCore.QSize(240, 41))
        self.email_3.setMaximumSize(QtCore.QSize(240, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.email_3.setFont(font)
        self.email_3.setObjectName("email_3")
        self.gridLayout.addWidget(self.email_3, 6, 2, 1, 1)
        self.email_5 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.email_5.setMinimumSize(QtCore.QSize(240, 41))
        self.email_5.setMaximumSize(QtCore.QSize(240, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.email_5.setFont(font)
        self.email_5.setObjectName("email_5")
        self.gridLayout.addWidget(self.email_5, 10, 2, 1, 1)
        self.line_58 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_58.setMinimumSize(QtCore.QSize(5, 5))
        self.line_58.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_58.setLineWidth(6)
        self.line_58.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_58.setObjectName("line_58")
        self.gridLayout.addWidget(self.line_58, 0, 1, 1, 1)
        self.line_63 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_63.setMinimumSize(QtCore.QSize(5, 5))
        self.line_63.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_63.setLineWidth(6)
        self.line_63.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_63.setObjectName("line_63")
        self.gridLayout.addWidget(self.line_63, 10, 1, 1, 1)
        self.email_4 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.email_4.setMinimumSize(QtCore.QSize(240, 41))
        self.email_4.setMaximumSize(QtCore.QSize(240, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.email_4.setFont(font)
        self.email_4.setObjectName("email_4")
        self.gridLayout.addWidget(self.email_4, 8, 2, 1, 1)
        self.line_69 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_69.setMinimumSize(QtCore.QSize(5, 5))
        self.line_69.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_69.setLineWidth(6)
        self.line_69.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_69.setObjectName("line_69")
        self.gridLayout.addWidget(self.line_69, 4, 3, 1, 1)
        self.line_60 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_60.setMinimumSize(QtCore.QSize(5, 5))
        self.line_60.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_60.setLineWidth(6)
        self.line_60.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_60.setObjectName("line_60")
        self.gridLayout.addWidget(self.line_60, 4, 1, 1, 1)
        self.line_89 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_89.setMinimumSize(QtCore.QSize(5, 5))
        self.line_89.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_89.setLineWidth(6)
        self.line_89.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_89.setObjectName("line_89")
        self.gridLayout.addWidget(self.line_89, 21, 1, 1, 1)
        self.line_72 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_72.setMinimumSize(QtCore.QSize(5, 5))
        self.line_72.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_72.setLineWidth(6)
        self.line_72.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_72.setObjectName("line_72")
        self.gridLayout.addWidget(self.line_72, 10, 3, 1, 1)
        self.line_65 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_65.setMinimumSize(QtCore.QSize(5, 5))
        self.line_65.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_65.setLineWidth(6)
        self.line_65.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_65.setObjectName("line_65")
        self.gridLayout.addWidget(self.line_65, 15, 1, 1, 1)
        self.line_64 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_64.setMinimumSize(QtCore.QSize(5, 5))
        self.line_64.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_64.setLineWidth(6)
        self.line_64.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_64.setObjectName("line_64")
        self.gridLayout.addWidget(self.line_64, 13, 1, 1, 1)
        self.line_62 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_62.setMinimumSize(QtCore.QSize(5, 5))
        self.line_62.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_62.setLineWidth(6)
        self.line_62.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_62.setObjectName("line_62")
        self.gridLayout.addWidget(self.line_62, 8, 1, 1, 1)
        self.line_77 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_77.setMinimumSize(QtCore.QSize(5, 5))
        self.line_77.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_77.setLineWidth(6)
        self.line_77.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_77.setObjectName("line_77")
        self.gridLayout.addWidget(self.line_77, 21, 3, 1, 1)
        self.line_71 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_71.setMinimumSize(QtCore.QSize(5, 5))
        self.line_71.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_71.setLineWidth(6)
        self.line_71.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_71.setObjectName("line_71")
        self.gridLayout.addWidget(self.line_71, 8, 3, 1, 1)
        self.line_66 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_66.setMinimumSize(QtCore.QSize(5, 5))
        self.line_66.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_66.setLineWidth(6)
        self.line_66.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_66.setObjectName("line_66")
        self.gridLayout.addWidget(self.line_66, 17, 1, 1, 1)
        self.line_74 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_74.setMinimumSize(QtCore.QSize(5, 5))
        self.line_74.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_74.setLineWidth(6)
        self.line_74.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_74.setObjectName("line_74")
        self.gridLayout.addWidget(self.line_74, 15, 3, 1, 1)
        self.line_68 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_68.setMinimumSize(QtCore.QSize(5, 5))
        self.line_68.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_68.setLineWidth(6)
        self.line_68.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_68.setObjectName("line_68")
        self.gridLayout.addWidget(self.line_68, 2, 3, 1, 1)
        self.line_67 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_67.setMinimumSize(QtCore.QSize(5, 5))
        self.line_67.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_67.setLineWidth(6)
        self.line_67.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_67.setObjectName("line_67")
        self.gridLayout.addWidget(self.line_67, 0, 3, 1, 1)
        self.line_73 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_73.setMinimumSize(QtCore.QSize(5, 5))
        self.line_73.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_73.setLineWidth(6)
        self.line_73.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_73.setObjectName("line_73")
        self.gridLayout.addWidget(self.line_73, 13, 3, 1, 1)
        self.line_88 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_88.setMinimumSize(QtCore.QSize(5, 5))
        self.line_88.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_88.setLineWidth(6)
        self.line_88.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_88.setObjectName("line_88")
        self.gridLayout.addWidget(self.line_88, 19, 1, 1, 1)
        self.line_76 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_76.setMinimumSize(QtCore.QSize(5, 5))
        self.line_76.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_76.setLineWidth(6)
        self.line_76.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_76.setObjectName("line_76")
        self.gridLayout.addWidget(self.line_76, 19, 3, 1, 1)
        self.line_75 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_75.setMinimumSize(QtCore.QSize(5, 5))
        self.line_75.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_75.setLineWidth(6)
        self.line_75.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_75.setObjectName("line_75")
        self.gridLayout.addWidget(self.line_75, 17, 3, 1, 1)
        self.sifre = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.sifre.setMinimumSize(QtCore.QSize(170, 41))
        self.sifre.setMaximumSize(QtCore.QSize(170, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sifre.setFont(font)
        self.sifre.setObjectName("sifre")
        self.gridLayout.addWidget(self.sifre, 2, 4, 1, 1)
        self.sifre_4 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.sifre_4.setMinimumSize(QtCore.QSize(170, 41))
        self.sifre_4.setMaximumSize(QtCore.QSize(170, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sifre_4.setFont(font)
        self.sifre_4.setObjectName("sifre_4")
        self.gridLayout.addWidget(self.sifre_4, 8, 4, 1, 1)
        self.sifre_8 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.sifre_8.setMinimumSize(QtCore.QSize(170, 41))
        self.sifre_8.setMaximumSize(QtCore.QSize(170, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sifre_8.setFont(font)
        self.sifre_8.setObjectName("sifre_8")
        self.gridLayout.addWidget(self.sifre_8, 17, 4, 1, 1)
        self.sira_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.sira_10.setMinimumSize(QtCore.QSize(27, 36))
        self.sira_10.setMaximumSize(QtCore.QSize(27, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sira_10.setFont(font)
        self.sira_10.setObjectName("sira_10")
        self.gridLayout.addWidget(self.sira_10, 21, 0, 1, 1)
        self.email_10 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.email_10.setMinimumSize(QtCore.QSize(240, 41))
        self.email_10.setMaximumSize(QtCore.QSize(240, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.email_10.setFont(font)
        self.email_10.setObjectName("email_10")
        self.gridLayout.addWidget(self.email_10, 21, 2, 1, 1)
        self.line_9 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_9.setMinimumSize(QtCore.QSize(5, 5))
        self.line_9.setSizeIncrement(QtCore.QSize(50, 50))
        self.line_9.setBaseSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.line_9.setFont(font)
        self.line_9.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.line_9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_9.setLineWidth(6)
        self.line_9.setMidLineWidth(0)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setObjectName("line_9")
        self.gridLayout.addWidget(self.line_9, 18, 0, 1, 5)
        self.sira_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.sira_2.setMinimumSize(QtCore.QSize(25, 36))
        self.sira_2.setMaximumSize(QtCore.QSize(25, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sira_2.setFont(font)
        self.sira_2.setObjectName("sira_2")
        self.gridLayout.addWidget(self.sira_2, 4, 0, 1, 1)
        self.sira_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.sira_9.setMinimumSize(QtCore.QSize(25, 36))
        self.sira_9.setMaximumSize(QtCore.QSize(25, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sira_9.setFont(font)
        self.sira_9.setObjectName("sira_9")
        self.gridLayout.addWidget(self.sira_9, 19, 0, 1, 1)
        self.sira_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.sira_5.setMinimumSize(QtCore.QSize(25, 36))
        self.sira_5.setMaximumSize(QtCore.QSize(25, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sira_5.setFont(font)
        self.sira_5.setObjectName("sira_5")
        self.gridLayout.addWidget(self.sira_5, 10, 0, 1, 1)
        self.sira_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.sira_4.setMinimumSize(QtCore.QSize(25, 36))
        self.sira_4.setMaximumSize(QtCore.QSize(25, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sira_4.setFont(font)
        self.sira_4.setObjectName("sira_4")
        self.gridLayout.addWidget(self.sira_4, 8, 0, 1, 1)
        self.sira_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.sira_7.setMinimumSize(QtCore.QSize(25, 36))
        self.sira_7.setMaximumSize(QtCore.QSize(25, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sira_7.setFont(font)
        self.sira_7.setObjectName("sira_7")
        self.gridLayout.addWidget(self.sira_7, 15, 0, 1, 1)
        self.sira_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.sira_6.setMinimumSize(QtCore.QSize(25, 36))
        self.sira_6.setMaximumSize(QtCore.QSize(25, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sira_6.setFont(font)
        self.sira_6.setObjectName("sira_6")
        self.gridLayout.addWidget(self.sira_6, 13, 0, 1, 1)
        self.line_21 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_21.setMinimumSize(QtCore.QSize(5, 5))
        self.line_21.setSizeIncrement(QtCore.QSize(50, 50))
        self.line_21.setBaseSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.line_21.setFont(font)
        self.line_21.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.line_21.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_21.setLineWidth(6)
        self.line_21.setMidLineWidth(0)
        self.line_21.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_21.setObjectName("line_21")
        self.gridLayout.addWidget(self.line_21, 23, 0, 1, 5)
        self.sira_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.sira_3.setMinimumSize(QtCore.QSize(25, 36))
        self.sira_3.setMaximumSize(QtCore.QSize(25, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sira_3.setFont(font)
        self.sira_3.setObjectName("sira_3")
        self.gridLayout.addWidget(self.sira_3, 6, 0, 1, 1)
        self.sira_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.sira_8.setMinimumSize(QtCore.QSize(25, 36))
        self.sira_8.setMaximumSize(QtCore.QSize(25, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sira_8.setFont(font)
        self.sira_8.setObjectName("sira_8")
        self.gridLayout.addWidget(self.sira_8, 17, 0, 1, 1)
        self.email_7 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.email_7.setMinimumSize(QtCore.QSize(240, 41))
        self.email_7.setMaximumSize(QtCore.QSize(240, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.email_7.setFont(font)
        self.email_7.setObjectName("email_7")
        self.gridLayout.addWidget(self.email_7, 15, 2, 1, 1)
        self.line_10 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_10.setMinimumSize(QtCore.QSize(5, 5))
        self.line_10.setSizeIncrement(QtCore.QSize(50, 50))
        self.line_10.setBaseSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.line_10.setFont(font)
        self.line_10.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.line_10.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_10.setLineWidth(6)
        self.line_10.setMidLineWidth(0)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setObjectName("line_10")
        self.gridLayout.addWidget(self.line_10, 20, 0, 1, 5)
        self.line_8 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_8.setMinimumSize(QtCore.QSize(5, 5))
        self.line_8.setSizeIncrement(QtCore.QSize(50, 50))
        self.line_8.setBaseSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.line_8.setFont(font)
        self.line_8.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.line_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_8.setLineWidth(6)
        self.line_8.setMidLineWidth(0)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setObjectName("line_8")
        self.gridLayout.addWidget(self.line_8, 16, 0, 1, 5)
        self.line_5 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_5.setMinimumSize(QtCore.QSize(5, 5))
        self.line_5.setSizeIncrement(QtCore.QSize(50, 50))
        self.line_5.setBaseSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.line_5.setFont(font)
        self.line_5.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.line_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_5.setLineWidth(6)
        self.line_5.setMidLineWidth(0)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setObjectName("line_5")
        self.gridLayout.addWidget(self.line_5, 9, 0, 1, 5)
        self.line_7 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_7.setMinimumSize(QtCore.QSize(5, 5))
        self.line_7.setSizeIncrement(QtCore.QSize(50, 50))
        self.line_7.setBaseSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.line_7.setFont(font)
        self.line_7.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.line_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_7.setLineWidth(6)
        self.line_7.setMidLineWidth(0)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setObjectName("line_7")
        self.gridLayout.addWidget(self.line_7, 14, 0, 1, 5)
        self.line_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_4.setMinimumSize(QtCore.QSize(5, 5))
        self.line_4.setSizeIncrement(QtCore.QSize(50, 50))
        self.line_4.setBaseSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.line_4.setFont(font)
        self.line_4.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.line_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_4.setLineWidth(6)
        self.line_4.setMidLineWidth(0)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 7, 0, 1, 5)
        self.line_22 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_22.setMinimumSize(QtCore.QSize(5, 5))
        self.line_22.setSizeIncrement(QtCore.QSize(50, 50))
        self.line_22.setBaseSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.line_22.setFont(font)
        self.line_22.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.line_22.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_22.setLineWidth(6)
        self.line_22.setMidLineWidth(0)
        self.line_22.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_22.setObjectName("line_22")
        self.gridLayout.addWidget(self.line_22, 1, 0, 1, 5)
        self.line_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_2.setMinimumSize(QtCore.QSize(5, 5))
        self.line_2.setSizeIncrement(QtCore.QSize(50, 50))
        self.line_2.setBaseSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.line_2.setFont(font)
        self.line_2.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setLineWidth(6)
        self.line_2.setMidLineWidth(0)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 3, 0, 1, 5)
        self.line_6 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_6.setMinimumSize(QtCore.QSize(5, 5))
        self.line_6.setSizeIncrement(QtCore.QSize(50, 50))
        self.line_6.setBaseSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.line_6.setFont(font)
        self.line_6.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.line_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_6.setLineWidth(6)
        self.line_6.setMidLineWidth(0)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setObjectName("line_6")
        self.gridLayout.addWidget(self.line_6, 12, 0, 1, 5)
        self.line_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_3.setMinimumSize(QtCore.QSize(5, 5))
        self.line_3.setSizeIncrement(QtCore.QSize(50, 50))
        self.line_3.setBaseSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.line_3.setFont(font)
        self.line_3.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.line_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_3.setLineWidth(6)
        self.line_3.setMidLineWidth(0)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 5, 0, 1, 5)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.save = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.save.setGeometry(QtCore.QRect(430, 590, 111, 51))
        self.save.setObjectName("save")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow2.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(MainWindow2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.toolBar.setFont(font)
        self.toolBar.setMouseTracking(False)
        self.toolBar.setObjectName("toolBar")
        MainWindow2.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionGiri = QtWidgets.QAction(MainWindow2)
        self.actionGiri.setObjectName("actionGiri")
        self.actionHesaplar_Ekle = QtWidgets.QAction(MainWindow2)
        self.actionHesaplar_Ekle.setObjectName("actionHesaplar_Ekle")
        self.actionBot_Ba_lar = QtWidgets.QAction(MainWindow2)
        self.actionBot_Ba_lar.setObjectName("actionBot_Ba_lar")
        self.actionGiri_2 = QtWidgets.QAction(MainWindow2)
        self.actionGiri_2.setObjectName("actionGiri_2")
        self.actionHesap_Ekle = QtWidgets.QAction(MainWindow2)
        self.actionHesap_Ekle.setObjectName("actionHesap_Ekle")
        self.actionBot_Ba_lat = QtWidgets.QAction(MainWindow2)
        self.actionBot_Ba_lat.setObjectName("actionBot_Ba_lat")
        self.toolBar.addAction(self.actionGiri_2)
        self.toolBar.addAction(self.actionHesap_Ekle)
        self.toolBar.addAction(self.actionBot_Ba_lat)

        self.retranslateUi(MainWindow2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow2)

    def retranslateUi(self, MainWindow2):
        _translate = QtCore.QCoreApplication.translate
        MainWindow2.setWindowTitle(_translate("MainWindow2", "MainWindow"))
        self.sira.setText(_translate("MainWindow2", "1"))
        self.email_isim.setText(_translate("MainWindow2", "E-mail"))
        self.sifre_isim.setText(_translate("MainWindow2", "Pass"))
        self.sira_10.setText(_translate("MainWindow2", "10"))
        self.sira_2.setText(_translate("MainWindow2", "2"))
        self.sira_9.setText(_translate("MainWindow2", "9"))
        self.sira_5.setText(_translate("MainWindow2", "5"))
        self.sira_4.setText(_translate("MainWindow2", "4"))
        self.sira_7.setText(_translate("MainWindow2", "7"))
        self.sira_6.setText(_translate("MainWindow2", "6"))
        self.sira_3.setText(_translate("MainWindow2", "3"))
        self.sira_8.setText(_translate("MainWindow2", "8"))
        self.save.setText(_translate("MainWindow2", "Save"))
        self.toolBar.setWindowTitle(_translate("MainWindow2", "toolBar"))
        self.actionGiri.setText(_translate("MainWindow2", "Giriş"))
        self.actionHesaplar_Ekle.setText(_translate("MainWindow2", "Hesapları Ekle"))
        self.actionBot_Ba_lar.setText(_translate("MainWindow2", "Bot Başlat"))
        self.actionGiri_2.setText(_translate("MainWindow2", "Giriş"))
        self.actionHesap_Ekle.setText(_translate("MainWindow2", "Hesap Ekle"))
        self.actionBot_Ba_lat.setText(_translate("MainWindow2", "Bot Başlat"))

